### ISSUE TITLE
Lumina - Fn key can't be mapped and the correct keyboard layout is loaded!

### ISSUE THREAD

**Issue by mike-pt** [pcbsd/lumina#1]
This is in continuation of:
https://github.com/pcbsd/pcbsd/issues/54

I'm guessing it not ideal to keep lumina issue there :)

The fix seems to work, volume down and up are detected and lower/raise the sounds!
Also, If I might add the suggestion it would be nice to see some feedback of this.... but so far I could config in the dashboard and mixer that it does change the sound!

The Fn+Left /right stilll returns (no more output):
Key Press: "0" "0" 
Key Press: "0" "0"

Pressing just Fn gives the same result!

Sidenotes:
- The fluxbox bottom bar is also gone which I reported in another issue!
- The clock plugin shows the seconds again (it was not showing seconds in some previous build, and tbh I prefer it because in laptops that will be once extra thing wasting the battery - should I open a new GHI about this?)

**Comment by mike-pt** [comment]
Sorry to bring this up again, I've been testing with "intel_backlight" (https://github.com/grembo/intel_backlight_fbsd) and also a patch in 11-Current that adds better support for backlight control ...

Anyway with intet_backlight and setting this:
 cat .lumina/fluxbox-keys |grep backlight
None 239        :Exec   intel_backlight decr
None 123        :Exec   intel_backlight incr

Backlight control works fine for me... I still can't set "fn-right" (123) or "fn-left" (239) tough lumina tough, but this brings me to a suggestion....

Could we also be able to add keycodes via the lumina-config GUI? might be useafull for such problems... but ofc nothing critical.

**Comment by beanpole135** [comment]
Interesting: does the fluxbox-keys lines work if you get rid of the "None" at the start of the line? If not, it might be something I can fix in Lumina really quickly because for special keycodes it currently just puts the number instead of "None <number>:" at the start. That might be a really quick/easy fix for this issue, since the Lumina seems to be able to detect the special keycodes fine (if the proper driver is in use). However, I will look into a manual option to set the keycode/command as well here soon.

**Comment by mike-pt** [comment]
sorry to bring this one up again... spcially cause I think lumina is not the issue.

I was able to set this up and point it to "intel_backlight" by using:

None    239     :Exec   intel_blacklight decr
None    123     :Exec   intel_blacklight incr


However xev is not reporting fn-left or fn-right with this keycodes anymore (at some point it did)

I just wonder if you have any idea why this would happen? Perhaps a xorg update "broke" it?


I've been using "model: acer_laptop" and layout "pt" as always:
```
setxkbmap -print
xkb_keymap {
        xkb_keycodes  { include "xfree86+aliases(qwerty)"       };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+pt+inet(acer_laptop)"       };
        xkb_geometry  { include "pc(pc104)"     };
};
```

**Comment by beanpole135** [comment]
I have actually been seeing a few people report issues like this with Xorg recently (on FreeBSD at least), so an Xorg change is probably the culprit in this case. 
`xev` is pretty much the final say on whether X itself is detecting the events, so I would say that something in Xorg probably changed recently and is causing the issues if you can't even find the events with `xev`.

**Comment by mike-pt** [comment]
Sorry never updated this one again.

xev seems to report  239 and 123 again when I press fn+left/right, so it was probably fixed.

Anyway since I'm here... would it make sense to detect if intel_backligh is instaleld and offer the choice to map keys to "intel_backlight" instead of lumina-open -brightness[up/down] ??

**Comment by beanpole135** [comment]
hm.. I am not familiar with `intel_backlight`, but that should be fairly easy to add in to the screen brightness routines in `libLumina/LuminaOS-<yourOS>.cpp`
Go ahead and send in any patches/updates to it, otherwise let me know the usage of `intel_backlight` and I can put it in for you.

**Comment by mike-pt** [comment]
hum, dunno if my c/c++ skills are good enough for that... I can print hello worlds and not much more that that :P 

I guess I can try and if I don't succeed or my patch sucks you can fix it :)


But for reference --> https://www.freshports.org/graphics/intel-backlight/

the usage is pretty much this:
intel_backlight ==> shows the current value
intel_backlight [incr|decr] (increments or decrements... after 50% its done by 10%, but from 1 to 50 its fixed: 1,6,9,16,20,25,30,36,43,51) at least in my experience :)

**Comment by beanpole135** [comment]
No problem, I will take a look at it next week then.  :-)

**Comment by mike-pt** [comment]
actually doesn't sound that hard cause you have half the job done:

```
  // - try hardware setting first (PC-BSD only)
  if(QFile::exists("/usr/local/bin/pc-sysconfig")){
    QString ret = LUtils::getCmdOutput("pc-sysconfig", QStringList() <<"setscreenbrightness "+QString::number(percent)).join("");
    success = ret.toLower().contains("success");
    qDebug() << "Set hardware brightness:" << percent << success;
  }
```

I'll give it a try ;)

**Comment by beanpole135** [comment]
sounds good - just let me know if you need help with anything!

**Comment by mike-pt** [comment]
Ok this is with a bit of debugging, not sure if the best way to do it... specially the `else if`, maybe there's a better approach to that.. but this is with what I know of c++ from head :p

git diff:
```
diff --git a/libLumina/LuminaOS-FreeBSD.cpp b/libLumina/LuminaOS-FreeBSD.cpp
index b5e92e0..fd7c990 100644
--- a/libLumina/LuminaOS-FreeBSD.cpp
+++ b/libLumina/LuminaOS-FreeBSD.cpp
@@ -82,8 +82,17 @@ void LOS::setScreenBrightness(int percent){
   else if(percent>100){ percent=100; }
   //Run the command(s)
   bool success = false;
-  // - try hardware setting first (PC-BSD only)
-  if(QFile::exists("/usr/local/bin/pc-sysconfig")){
+  // - try hardware setting first (PC-BSD || or intel_backlight)
+  if(QFile::exists("/usr/local/bin/intel_backlight")){
+    qDebug() << "/usr/local/bin/intel_backlight" << "was found!";
+    QString ret = LUtils::getCmdOutput("intel_backlight", QStringList() <<QString::number(percent)
+).join("");
+    success = ret.toLower().contains("success");
+    qDebug() << "Set hardware brightness:" << percent << success;
+    // Check if percentage = intel_backlight
+    qDebug() << "intel_backlight:" << LUtils::getCmdOutput("intel_backlight");
+  }
+  else if((QFile::exists("/usr/local/bin/pc-sysconfig")) && (!QFile::exists("/usr/local/bin/intel_bac
     QString ret = LUtils::getCmdOutput("pc-sysconfig", QStringList() <<"setscreenbrightness "+QString
     success = ret.toLower().contains("success");
     qDebug() << "Set hardware brightness:" << percent << success;
diff --git a/lumina-xconfig/i18n/lumina-xconfig_pt.ts b/lumina-xconfig/i18n/lumina-xconfig_pt.ts
index b3cbf87..a0d493b 100644
--- a/lumina-xconfig/i18n/lumina-xconfig_pt.ts
+++ b/lumina-xconfig/i18n/lumina-xconfig_pt.ts
```

Testing output:
```
[miguelc@r2d2:~ ]% lumina-open -brightnessup
Loading System Encoding: "UTF-8"
/usr/local/bin/intel_backlight was found!
Set hardware brightness: 65 false
intel_backlight: ("current backlight value: 65% (634/976)", "")
Loading Locale: "lumina-open" "en_US" "UTF-8"
Fontconfig warning: "local.conf", line 1093: saw number, expected matrix
Display OSD
[miguelc@r2d2:~ ]% lumina-open -brightnessdown
Loading System Encoding: "UTF-8"
/usr/local/bin/intel_backlight was found!
Set hardware brightness: 60 false
intel_backlight: ("current backlight value: 60% (586/976)", "")
Loading Locale: "lumina-open" "en_US" "UTF-8"
^[[AFontconfig warning: "local.conf", line 1093: saw number, expected matrix
Display OSD
[miguelc@r2d2:~ ]% lumina-open -brightnessdown
Loading System Encoding: "UTF-8"
/usr/local/bin/intel_backlight was found!
Set hardware brightness: 55 false
intel_backlight: ("current backlight value: 55% (537/976)", "")
Loading Locale: "lumina-open" "en_US" "UTF-8"
Fontconfig warning: "local.conf", line 1093: saw number, expected matrix
Display OSD
```

And I just realise that `false` should be `true` and this is making it change both hardware backlight and xbrightness ...

probably related to the output of `LUtils::getCmdOutput("intel_backlight", QStringList() <<QString::number(percent)
).join("");` 

well not bad for the first try ;)

gonna fix that and then submit a PR

**Comment by beanpole135** [comment]
Ok, your update for intel_backlight support was just added in - thanks for working on that!
