### ISSUE TITLE
Having a "Open terminal" in fm

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#101]
I often use the feature of thunar which allow the user to open a terminal in a specific directory. I think the following code could be a good basis : 
https://github.com/william-os4y/lumina/commit/666e3b70b6b1936c2b1dd67c48b521b43077b149

Up to you to use it/improve it/drop it. 

Many thanks

**Comment by beanpole135** [comment]
That looks good!
Go ahead and send in a pull request and we can get that added in before 0.8.4-release is tagged here soon. The only thing I see which it might need is to enclose the directory path within single-quotes as well (just in case a directory has spaces in the name). I don't see a problem with forcing the use of xterm at the moment - we can do some research to see if the majority of terminal applications respect that "-e" flag for backwards compatibility with xterm before switching it over to use the user-specified terminal application instead.

**Comment by william-os4y** [comment]
Inded the "-e" is specific to xterm.
I'll check how xfce is managing this. But, if I' remember well they are
only using their own terminal.

**Comment by beanpole135** [comment]
I just looked up the xfce4-terminal options, and they also respect the "-e" flag for CLI usage (that is actually the terminal I use on my main system instead of xterm).
The other big ones I can think of that we need to check on are:
rxvt[-unicode]
konsole
terminator
eterm (from the enlightenment project)
Perhaps there are a couple others as well?

**Comment by william-os4y** [comment]
Sounds that the -e <command> is generic

rxvt: http://linux.die.net/man/1/rxvt
konsole: http://manpages.ubuntu.com/manpages/hardy/man1/konsole.1.html
eterm: http://www.eterm.org/docs/view.php?doc=man

**Comment by beanpole135** [comment]
I just merged in your pull request which enables this feature in lumina-fm:
Thanks for working on that!
