### ISSUE TITLE
how to add a grey background on the incons of the desktop ?

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#106]
Most of the background pictures (for desktop)  are dark. Unfortunately the text of the icons on the desktop is black too. 
Would be nice to have a small halo/background in grey (like you can have in xfce). 

I've tried to do it via the "theme template", but I've not succeed. 

thanks for your help

**Comment by beanpole135** [comment]
I have a few different "hooks" in the theme file for things like this, but I am not sure if there is a Qt hook for applying background colors to "just" the text for a QListWidgetItem.
Some of the Lumina-specific hooks:
* Change the font color to something lighter-colored (I use an almost-white for my fonts on a dark-colored theme)
* "LDPlugin#LuminaDesktopPlugin{}" is the overall settings for the desktop plugins which allow invisibility (such as the desktopview plugin).

You might be able to do something more complicated with widget parentage like:
"LDPlugin#LuminaDesktopPlugin QListView::item{}"
That "should" (although I have not tried it) allow you to customize just the individual icons within the desktopview plugin.

Some info about StyleSheets that I use for reference is here: http://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qlistview

**Comment by william-os4y** [comment]
Thanks Ken. By changing the backgrouund of LDPlugin#LuminaDesktopPlugin I change it for the whole area. 
I was looking for something limited to the text zone like in XFCE:
http://fedoraproject.org/w/uploads/c/c2/XFCE_Desktop.png
(Look at "home", file system", ...)

I've added a "color" entry in LDPlugin#LuminaDesktopPlugin, but it has not changed the color of the text. Am I missing something ?

**Comment by beanpole135** [comment]
If you specifically want to change the color of the font *only* in the "invisible background" desktop plugins, then try this:
`LDPlugin#LuminaDesktopPlugin .QWidget{
  color: white;
}`

The plugin container itself does not have any fonts (which is probably why it is not working for you), you need to apply that setting to it's children widgets.

**Comment by william-os4y** [comment]
Many thanks !!!! 
I've changed it a little bit and the exact CSS is:
LDPlugin#LuminaDesktopPlugin QWidget{ 
color: %%SECONDARYCOLOR%%; 
}

the "." before QWidget was not correct.

**Comment by william-os4y** [comment]
The solution is the following:

LDPlugin#LuminaDesktopPluginVisible{
  background: %%ACCENTDISABLECOLOR%%;
  border: 1px solid transparent;
  border-radius: 5px;
}
(I've just replce the backghround transparent by ACCENTDISABLECOLOR)

With this change the text bellow the icon will be black on a grey background. Excatly like XFCE. 
Better than white color. 

But now the other Icons on the desktop (created via the application launcher) are not adapted. 
How to change those too ?

**Comment by beanpole135** [comment]
The stand alone "applauncher" plugin is based on a QToolButton I believe, so you would do something similar, but specifically targetting the QToolButton child widgets:
`LDPlugin#LuminaDesktopPlugin QToolButton{ background: %%ACCENTDISABLECOLOR%%; }`

This actually makes me wonder if we can start tagging each of the different base plugins widgets by the name of the plugin so this type of thing is easier to perform: for example, LDPlugin#desktopview, or LDPlugin#applauncher. If I remember right, the "#[name]" comes from the ObjectName() which is set for the widget:
`this->setObjectName(QString something)`

**Comment by beanpole135** [comment]
Ok, I just put in a quick change to move from the "LuminaDesktopPlugin[Visible]" tags to plugin-specific tags. Just un-comment line 43 in lumina-desktop/desktop-plugins/LDPlugin.h to enable it and rebuild your lumina-desktop session to start playing with it. I am guessing that it will break the visuals for almost all the desktop plugins (so the stylesheet will need quite a bit of adjusting to fix it up again), but this might be what we need to do in the long-term for finer-grained control of the visuals.
I won't have that much time to test it out this weekend/early next week, so if you want to see what you can come up with, I would be happy to pull it into the main tree sometime later next week!

**Comment by william-os4y** [comment]
Based on the change you proposed on May 2nd, the following is working very fine :-). 

The only issue (not sure from where this come from) is linked to the contextmenu background color. 
On the desktopview the background is white, on the applauncher it's black. 

```
LDPlugin#desktopview QListWidget{
  background: transparent;
}

LDPlugin#applauncher  QWidget{
background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
  stop: 0 transparent, 
  stop: 0.7 transparent,
  stop: 1.0 %%ACCENTDISABLECOLOR%%);
  border-radius: 5px; 
  color: %%ALTBASECOLOR%%;
}

LDPlugin#desktopview QListWidget::item{
  background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
  stop: 0 transparent, 
  stop: 0.7 transparent,
  stop: 1.0 %%ACCENTDISABLECOLOR%%);
  border-radius: 5px; 
  color: %%ALTBASECOLOR%%;
}
 
```

**Comment by william-os4y** [comment]
A much better solution, to my eyes is the following:

```
LDPlugin#applauncher  QWidget{
background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
  stop: 0 transparent, 
  stop: 0.7 transparent,
  stop: 1.0 %%ACCENTDISABLECOLOR%%);
  border-radius: 5px; 
  color: %%ALTBASECOLOR%%;
}
LDPlugin#applauncher  QWidget:hover{
  background: %%ACCENTDISABLECOLOR%%;
  border-radius: 5px; 
  color: %%ALTBASECOLOR%%;
}

LDPlugin#desktopview QWidget{
  background: transparent;
  border: 1px solid transparent;
}

LDPlugin#desktopview QListWidget::item{
  background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
  stop: 0 transparent, 
  stop: 0.7 transparent,
  stop: 1.0 %%ACCENTDISABLECOLOR%%);
  border-radius: 5px;
  color: %%ALTBASECOLOR%%;
}

LDPlugin#desktopview QListWidget::item:hover{
  background: %%ACCENTDISABLECOLOR%%;
  border-radius: 5px;
  color: %%ALTBASECOLOR%%;
}

```

I'll try to find the correct file and propose push-request.

**Comment by beanpole135** [comment]
You need to be careful with transparency on Qt, because it is not a window-manager compositor, only a parent-child compositor. This is why your context menu is black when you tell it to be transparent, because it does not have a parent Qt window to pull from (a context menu is a top-level window from my experience).

**Comment by beanpole135** [comment]
Your new changes are now included in the next version of libLumina[1].

Thanks for sending it in!

https://github.com/pcbsd/lumina/pull/111

**Comment by william-os4y** [comment]
Ken,

based on the last changes, I propose to adapt the color scheme for Text
Highlighted to something like rgb(171,171,171).

W.

**Comment by william-os4y** [comment]
Ken,

My last proposal has some bad side effects.

I could suggest to not change the color scheme, but have in the theme
template "color: %%TEXTDISABLECOLOR%%" for "LDPlugin#applauncher
QToolButton:hover" and "LDPlugin#desktopview QListWidget::item:hover"

W.

**Comment by beanpole135** [comment]
Color schemes are designed to work together in groups, which is why in the theme template should stick to using only the colors specified in the current scheme.

I actually think the font color for the "hover" states needs to stay with the %%TEXTHIGHLIGHT%% color because when the user hovers the mouse over an item, you want to be sure that the font is easily readable. Since the items already use the ACCENTDISABLECOLOR for the background, the FONTDISABLECOLOR (usually) has the tendency to blend into that background a bit while the TEXTHIGHLIGHTCOLOR should stand out a bit more (again, this is dependant on how the color scheme is setup).

It might be more advantageous, to tweak the color scheme your are using to create the effect you are looking for. This should ensure a broader application of those effects and unify the appearance across the entire desktop. The other alternative would be to change the color used for the background of the desktop icons, maybe just ACCENTCOLOR or one of the SECONDARYCOLOR's instead of the current disable color.
