### ISSUE TITLE
(Linux) System Dashboard is loaded, but missing

### ISSUE THREAD

**Issue by ryanpcmcquen** [pcbsd/lumina#112]
It could be there is a missing dependency I don't have, but everything else appears to be working. I am running Slackware, using this build script:
http://slackbuilds.org/repository/14.1/desktop/lumina/
http://slackbuilds.org/slackbuilds/14.1/desktop/lumina/lumina.SlackBuild

This is for the older Qt4 version (0.7.2).

Thanks!

**Comment by beanpole135** [comment]
Most of the system dashboard functionality is based on the LuminaOS interface/class, so the first thing to check is that the version of LuminaOS you are compiling into Lumina functions on Slackware (I assume you are using the generic "Linux" version, I am not terribly familiar with the syntax of slackware build scripts and I don't see where the build instructions are setup).

I *highly* recommend updating the build to use the new Qt5-based versions (0.8.4 right now). There are massive numbers of improvements/fixes in it, and this issue with the system dashboard might just be something that was fixed quite a while ago.

**Comment by ryanpcmcquen** [comment]
I will try the newer branch, thank you!
