### ISSUE TITLE
Lumina-fm does not remember the previous position when you "go-back" to parent folder

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#114]
To reproduce the problem:
- imagine you have a folder (call it parentfolder) with 100 sub-folders. 
- you scroll down and double click to open one of the sub-folder
- when you go-back (left arrow) lumina-fm display the parentfolder, but not at the position where we were. You still have to scroll down again. 

For example Thunar positions, in the parentfolder,  the sub-folder previously visited at the top of the screen. This occurs  when you do "go-back" and even when you do "go-up".

**Comment by beanpole135** [comment]
Hum.. I think this might be doable since it should already have knowledge of the previously-opened directory (and can just scroll the widget down so that item is visible). I will take a look at it here soon and see what I can do.

**Comment by beanpole135** [comment]
Ok, I just added support for this in lumina-fm. Give it a shot and see if that works for you now.

**Comment by william-os4y** [comment]
Hello Ken,

Indeed, when I "go-back" (and go-up), it shows the parent folder and it
places it at the bottom of the screen.
To be perfect I propose to add the following parameter
QAbstractItemView::PositionAtTop.


This has no effect when I select the view mode "Basic list". But this was
expected so.

**Comment by beanpole135** [comment]
Done!

https://github.com/pcbsd/lumina/commit/dee81bf75faf2d894b4801d5ea79318d7f41b682

**Comment by william-os4y** [comment]
many thanks
