### ISSUE TITLE
lumina-open generate some crashes. 

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#119]
I do a "open terminal here" and the whole lumina crash. 

I don't know which info you need. 

here the gdb:
(gdb) bt
#0  0x00001ce906b5390a in kill () at <stdin>:2
#1  0x00001ce906b8d0b9 in abort () at /usr/src/lib/libc/stdlib/abort.c:53
#2  0x00001ce89cc39d86 in QMessageLogger::fatal () from /usr/local/lib/qt5/libQt5Core.so.0.0
#3  0x00001ce907a73617 in QXcbConnection::QXcbConnection () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#4  0x0000014200000001 in ?? ()
#5  0x00001ce907bd29d0 in typeinfo name for INCRTransaction () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#6  0x00001ce907bd3f20 in _ZZL14ioErrorHandlerP9_XDisplayE19__PRETTY_FUNCTION__ () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#7  0x00001ce907bd1c51 in ?? () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#8  0x0000000000000002 in ?? ()
#9  0x00001ce8d4b229e0 in ?? ()
#10 0x00007f7ffffcf2ac in ?? ()
#11 0x00001ce906b8bf1c in malloc (size=64) at /usr/src/lib/libc/stdlib/malloc.c:1181
#12 0x00007f7ffffcefa0 in ?? ()
#13 0x00001ce948d73400 in ?? ()
#14 0x00001ce91fb45800 in ?? ()
#15 0x0000000000000008 in ?? ()
#16 0x00001ce8d4b229e0 in ?? ()
#17 0x00007f7ffffcf2ac in ?? ()
#18 0x00001ce907a7575e in QXcbIntegration::QXcbIntegration () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#19 0x00001ce907a876fb in QXcbIntegrationPlugin::create () from /usr/local/lib/qt5/plugins/platforms/libqxcb.so
#20 0x00001ce8e70add9f in QPlatformIntegrationFactory::create () from /usr/local/lib/qt5/libQt5Gui.so.0.0
#21 0x00001ce8e70b87b6 in QGuiApplicationPrivate::createPlatformIntegration () from /usr/local/lib/qt5/libQt5Gui.so.0.0
#22 0x00001ce8e70b967d in QGuiApplicationPrivate::createEventDispatcher () from /usr/local/lib/qt5/libQt5Gui.so.0.0
#23 0x00001ce9535a0a00 in ?? ()
#24 0x00001ce89cdfca51 in QCoreApplication::init () from /usr/local/lib/qt5/libQt5Core.so.0.0
#25 0x00001ce87e09a700 in ?? ()
#26 0x00001ce89d1c1810 in vtable for QCoreApplication () from /usr/local/lib/qt5/libQt5Core.so.0.0
#27 0x00007f7ffffcf370 in ?? ()
#28 0x00001ce9535a0a00 in ?? ()
#29 0x00007f7ffffcf2ac in ?? ()
---Type <return> to continue, or q <return> to quit---
#30 0x00001ce89cdfcac6 in QCoreApplication::QCoreApplication () from /usr/local/lib/qt5/libQt5Core.so.0.0
#31 0x00001ce8e70bbaa9 in QGuiApplication::QGuiApplication () from /usr/local/lib/qt5/libQt5Gui.so.0.0
#32 0x00001ce8ead22bfd in QApplication::QApplication () from /usr/local/lib/qt5/libQt5Widgets.so.0.0
#33 0x00001ce679a0df58 in main () from /usr/local/bin/lumina-open
Current language:  auto; currently asm
(gdb) 

in logs/runtime.log there is nothing (at least nothing relevant)

**Comment by beanpole135** [comment]
Yikes! What was the command you were running with lumina-open? I don't really see anything in particular from the gdb output which sheds any light on why the crash occured.

**Comment by william-os4y** [comment]
I can reproduce the problem (but it's not linked to lumina-open):
- create a calendar desktop plugin
- unlock the desktop
- close the window of the calendar plugin

This crash my whole lumina desktop with a core dump of Lumina-DE and fluxbox.

**Comment by beanpole135** [comment]
I will see if I can reproduce this here. I know that I fixed a number of desktop plugin crashe-issues related to removals a little bit ago, but I can verify that again.

**Comment by beanpole135** [comment]
Ok, I was finally able to track down and fix the crash when removing a desktop plugin. It seems like it was CPU/time sensitive - so it took a little bit for me to find a system which exhibited this issue on a consistent basis. If you rebuild from the latest sources it should be fixed for you know... :-)
