### ISSUE TITLE
Not possible to associate .info file with firefox

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#120]
Hello, 

I've installed firefox and ask him to save a page for "off-line" reading. 
It generates an .info file. 

I right click it and select firefox as "default application" (I flag it). It opens it with firefox. Perfect. 

But in fact this association is not registered somewhere because if I double click on this .info file he does not open it with firefox. 

I know that this topic is really linked to setup of my machine and presence of correct .desktop files, ... 

Can you reproduce it ?

**Comment by beanpole135** [comment]
How did you set firefox as the default application? In the lumina-open dialog or in firefox itself?

**Comment by william-os4y** [comment]
In lumina-fm, I right click on the .info file and select "open width", then
select firexox and check the box "set this as default", then click "ok".

it open the file with firefox perfectly.

I thought that the association will be registered but it does not work. If
I double click on the .info file, firefox does not start.


I did the same for .txt with juffed and it was perfect. Now I double click
on a .txt and juffed starts.

So, it's strange that it works for some extensions and not all.

**Comment by beanpole135** [comment]
I am looking into this now. My guess would be that there are more than one mimetype associated with .info files (since defaults are mimetype-based), and the default application was only getting set for one of them.

**Comment by beanpole135** [comment]
Ok, it looks like there is no mimetype for `*.info` files/globs in the XDG database by default - hence the issues. You can check by looking through your `/usr/local/share/mime/globs2` file for anything matching `*.info` (I could not find anything). So it looks like I need to put in some fallback methods for Lumina to assign a temporary "non-mimetype" based on the file extension for the default application registrations....

**Comment by beanpole135** [comment]
Ok, I just fixed this in libLumina.
Now it will assign files that do not have a corresponding mimetype with one like this: "unknown/[extension]" or "unknown/[filename]" as appropriate. This fixes the issues with .info files on my system.

**Comment by william-os4y** [comment]
works perfect.

Thanks
