### ISSUE TITLE
lumina will not build on PowerPC

### ISSUE THREAD

**Issue by JR1994** [pcbsd/lumina#136]
I just installed FreeBSD on my iBook G4. I have Xorg configured and working, but when I tried to get lumina installed I get an error when trying to compile telling to use this option *MAKE_JOBS_UNSAFE=yes*. So I tried to install with the option: *make MAKE_JOBS_UNSAFE=yes install clean*. Still it failed to build. I took a picture of the error and am attaching it.

![img_1683](https://cloud.githubusercontent.com/assets/5367328/8650692/17ccf2de-293a-11e5-8a6d-816c59da32df.JPG)

**Comment by beanpole135** [comment]
Looks like the problem is actually in building qmake (part of Qt5) on PowerPC. You might want to post a bug report on the FreeBSD bug tracker[1] instead, so the maintainers of the Qt5 ports can get that fixed..

[1] https://www.freebsd.org/support/bugreports.html

**Comment by JR1994** [comment]
Thanks will do!
