### ISSUE TITLE
insight-fm: Use mouse buttons 4 and 5 for navigating back/forth

### ISSUE THREAD

**Issue by mneumann** [pcbsd/lumina#148]
Would be nice if these mouse buttons would work in insight-filemanager in the same way
as they work in other filemanagers or firefox.

**Comment by q5sys** [comment]
Or have all the mouse buttons in general be user definable. Certain mice
identify button 4 and 5 differently based on the design.  However I admit
that I have no idea how much extra work that would be.

**Comment by mneumann** [comment]
+1 for user definable.

**Comment by beanpole135** [comment]
Noted: I also think this is a good idea, and I will look into it here soon.

**Comment by beanpole135** [comment]
Ok, since lumina-fm does not have a "forward" button at the moment, I only implemented the "Back" mouse button functionality. Since I do not have a 4/5 button mouse at the moment, would you mind testing it out and making sure it is functional?

Qt Mouse button definitions: http://doc.qt.io/qt-5/qt.html#MouseButton-enum
Commit: https://github.com/pcbsd/lumina/commit/a11748f3e7d40d87943767c40676cca4a613eb95

**Comment by mneumann** [comment]
@beanpole135 : It's not working :(

**Comment by beanpole135** [comment]
Hmm.. Sounds like I need to go pick up a cheap 4/5 button mouse.... :-)

**Comment by q5sys** [comment]
I only have 2 button mice and a spare 8 button trackball.  Otherwise I'd
mail you one to use.
Is xev in freebsd, anything else I could do to capture data for you during
button presses?
~JT

**Comment by mneumann** [comment]
Ok, it's button 8 (and 9) on my computer.

**Comment by beanpole135** [comment]
Ok, I just fixed this up - see if it works now.

**Comment by mneumann** [comment]
works! thanks! one thing I noticed is that you can move/copy files with button8, which I guess should be forbidden. I noticed it, when I was still moving the mouse while pressing the button8 (to test 'back').

**Comment by beanpole135** [comment]
Good Catch!
I will make sure to de-activate the non-left/right mouse buttons for drag operations here in a moment.
