### ISSUE TITLE
Consider forbidding screen brightness below ~10%

### ISSUE THREAD

**Issue by mneumann** [pcbsd/lumina#150]
When accidentially setting the screen brightness below 10% (easy to do so by moving the slider), the screen turns black, and it's very difficult to recover from that situation. I question the usefullness of setting it below 10%. It would be more useful to have a "save power button", which works like a screensaver, i.e. when you hit it, the screen turns black until you move the mouse.

**Comment by beanpole135** [comment]
That is a good idea. I will look into setting the lower limit to 10% for the UI sliders (keyboard shortcuts can still go lower as necessary).

**Comment by beanpole135** [comment]
Done!
Both the system dashboard and the new start menu plugin now have a lower limit of 10% for the screen brightness setting.

**Comment by mneumann** [comment]
Great!
