### ISSUE TITLE
Desktop Configuration app takes +90 seconds to load when many backgrounds are available

### ISSUE THREAD

**Issue by rubin55** [pcbsd/lumina#156]
Using Lumina 0.8.6 on FreeBSD 10.2 via Ports.

The Desktop Configuration app, which contains the Appearance, Interface, Applications, Shortcuts and Session settings, will take a very long time to load (I've seen between 70 and 90 seconds on my system) when a large collection of backgrounds is added (via the Wallpaper tab on the Appearance settings screen).

I've selected 160 backgrounds which rotate every 60 minutes (which works like expected).

**Comment by beanpole135** [comment]
Yeah, I just ran into this recently as well - it is trying to load the thumbnails for all the various wallpapers before the app becomes usable. Working on a fix right now....

**Comment by beanpole135** [comment]
Done!
I just set it up to skip the initial loading of the wallpaper thumbnails, and instead it will set the thumbnail for the current item every time you change which wallpaper is being previewed.

https://github.com/pcbsd/lumina/commit/b43405f779e3c853f24901d5f89d699d9c899f3f
