### ISSUE TITLE
Lumina theme breakage at session initialization

### ISSUE THREAD

**Issue by rubin55** [pcbsd/lumina#157]
Using Lumina 0.8.6 on FreeBSD 10.2 via Ports.

1: When starting Lumina for the very first time, I see the default desktop.
2: When I quit my X session and startx again (which executes my .xinitrc which contains exec /usr/local/bin/Lumina-DE), I get a strange issue. In the attached screenshot You'll see two issues that stand out: The panel bar lost its color, and that small square in the corner is actually the Desktop Icon area.

Going into Desktop Configuration -> Appearance -> Theme  -> Theme Template and setting "Lumina-default (System)" to "None (System)" resets the theme and the desktop looks normal again. Then reselecting "Lumina-default (System)" works as expected.

![lumina theme breakage strange desktop size](https://cloud.githubusercontent.com/assets/6214491/9901280/d6712bec-5c66-11e5-98d6-c896fe4e920f.png)

**Comment by rubin55** [comment]
I found out why this happens. In my .profile there is a line:
    export QT_QPA_PLATFORMTHEME=qt5ct
This confuses Lumina and results in this issue.

**Comment by beanpole135** [comment]
Good catch!
I just added a quick check/purge of that environment variable before starting up the Lumina desktop session. This should allow you to keep that setting for other DE's and it won't impact Lumina any more.
