### ISSUE TITLE
Add local fluxbox theme into config

### ISSUE THREAD

**Issue by lbartoletti** [pcbsd/lumina#159]
Lumina can use local fluxbox themes (~/.fluxbox/styles/YOURTHEME) by writing in hard into ~/.lumina/fluxbox-init. For example:
`session.styleFile:	~/.fluxbox/styles/solarized`

But lumina-config not allow to choose a style into local fluxbox styles unlike lumina themes.

**Comment by beanpole135** [comment]
Fixed!
https://github.com/pcbsd/lumina/commit/32ce4568da9ea61b4dafaf8022d48bdda57ec5b2
