### ISSUE TITLE
iXsystems Logo

### ISSUE THREAD

**Issue by possnfiffer** [pcbsd/lumina#161]
![oldixlogo](https://cloud.githubusercontent.com/assets/773239/10711515/d69b8792-7a3a-11e5-9f22-11ead833a75a.png)
Are you planning on updating the iXsystems logo on this Lumina Desktop Information screen?

**Comment by beanpole135** [comment]
Thanks for catching that!
I will get that logo updated here in a few minutes. This change misses the release deadline for 0.8.7, but it will be included in future releases.
