### ISSUE TITLE
removing GUI blocking behavior of "LUtils::getCmdOutput"

### ISSUE THREAD

**Issue by mhogomchungu** [pcbsd/lumina#162]
greetings,

I was going through your sources to see how you guys are doing a few things and i came across this function[1] that does GUI blocking operations that may be upto 30 seconds[2][3] which is not good. GUI programming

Can i interest you guys to my task[4] library that will give the "LUtils::getCmdOutput" function the same outside behavior but without its current GUI blocking behavior?.

With my library the implementation of the function can be something like below:

```
QStringList LUtils::getCmdOutput(QString cmd, QStringList args){
  return Task::await<QStringList>([&](){
    QProcess proc;
    QProcessEnvironment env = QProcessEnvironment::systemEnvironment();
    env.insert("LANG", "C");
    env.insert("LC_MESSAGES", "C");
    proc.setProcessEnvironment(env);
    proc.setProcessChannelMode(QProcess::MergedChannels);
    if(args.isEmpty()){
      proc.start(cmd);
    }else{
      proc.start(cmd,args);
    }
    if(!proc.waitForStarted(30000)){ return QStringList(); } //process never started - max wait of 30 seconds

    proc.waitForFinished(-1);

    return QString(proc.readAllStandardOutput()).split("\n");

    });
}
```
[1] https://github.com/pcbsd/lumina/blob/31a119ea305df365406f5130fcf068fd36a59506/libLumina/LuminaUtils.cpp#L49

[2] https://github.com/pcbsd/lumina/blob/31a119ea305df365406f5130fcf068fd36a59506/libLumina/LuminaUtils.cpp#L61

[3] http://doc.qt.io/qt-5/qprocess.html#waitForStarted

[4] https://github.com/mhogomchungu/tasks

**Comment by beanpole135** [comment]
Well, all your function does is change the piece which prevents the thread from getting **too** stale into one which will stop the main event loop for as long as it takes for the process to finish:
> `proc.waitForFinished(-1)` instead of `while(!proc.waitForFinished(500)){
>    if(proc.state() != QProcess::Running){ break; } //somehow missed the finished signal
>    QCoreApplication::processEvents();
>  }`

I will adjust the routine in a few moment to one that will properly remove that "waitForStarted()" function call.

**Comment by beanpole135** [comment]
Here you go:

https://github.com/pcbsd/lumina/commit/ca3e2f9d793d8a839048f8daabd276556a861380

**Comment by beanpole135** [comment]
Ok, I just noticed your "Task::await()" wrapper function call and took a peek at the description of that function in your library. To achieve the exact same behavior with Qt (run a function in a background thread), it is much simpler to use the QtConcurrent module/extension (which I already use in other Lumina subprojects), so I just converted those two functions in the Lumina library to use that system for running/monitoring the external process[1]. Thanks for bringing this to my attention!

https://github.com/pcbsd/lumina/commit/eebcb9b10e97ed2241bb1792e7b3ec54b6b3e94e

**Comment by mhogomchungu** [comment]
I guess your new function is an improvement from the old one but it still blocks the main thread and prevents event processing for 300 milliseconds preventing accurate event processing necessitating your manual check for process state.

Have you though about what other event from where else could be missed due to the blocking that is happening here? Your doing this blocking from a library that sits at the heart of your application.

```
Well, all your function does is change the piece which prevents the thread from getting too stale into one which will stop the main event loop for as long as it takes for the process to finish:
```
That is not true,my version will NOT stop the main event loop at all and this is the biggest difference between my version and yours.Yours blocks the current(main) thread,prevents events processing and freezing the GUI in the process,mine does none of these.

async programming is the new thing in languages these days and it maybe useful in looking it up to see what problems they are trying to solve.In my project page,i have included links to proposals on how to include the await functionality in future versions of C++.

Your comment above that says my version will stop the main event loop seems to suggest you do not have an understanding on how the await functionality works.

**Comment by beanpole135** [comment]
Here you go: http://doc.qt.io/qt-5/qtconcurrent-index.html

In particular, I used the QtConcurrent::run() functionality for the Lumina library, although you can see many other multi-threading options in the module as well.

**Comment by mhogomchungu** [comment]
That function returns QFuture<T> and it has the same behavior as std::future<T>,they could potentially block[1][2] when the result of the future is claimed before it is available.

Your new function just moved from "provably blocking" to "potentially blocking" :-)

[1] http://doc.qt.io/qt-5/qfuture.html#result
[2] http://en.cppreference.com/w/cpp/thread/future/get

**Comment by mhogomchungu** [comment]
When it comes to async programming, QFuture<T> and std::future<T> solves half of the problem and "then" or "await" functionality solves the remaining half of the problem but Qt as a framework and C++ as a language currently do not have a solution to the remaining half of the problem.

My library solves the complete problem using Qt's APIs and a compiler that supports C++11 only.

**Comment by beanpole135** [comment]
Interesting - you might want to bring this up with the Qt project itself and get your work included out of box within their QtConcurrent/QFuture classes then. I am just extremely hesitant to bring in any additional dependencies into the Lumina project, especially when it comes to supporting/maintaining ports to 3rd-party code on the BSD's (not to mention possible licensing issues). If you get it included in the next version of Qt5 then I will use it gladly!

**Comment by mhogomchungu** [comment]
They are already aware of my project: http://lists.qt-project.org/pipermail/development/2014-July/017604.html
