### ISSUE TITLE
enabling IRC webchat link from desktop

### ISSUE THREAD

**Issue by rockworldmi** [pcbsd/lumina#168]
we can add link to webchat IRC "https://webchat.freenode.net/?channels=%23lumina-desktop" for new users who just start using Lumina

**Comment by beanpole135** [comment]
This is a good idea.
I am having issues connecting to the freenode web client right now (through both the freenode and kiwiirc webclients), so I can't verify the link/URL yet - but I have two options for this:

1) Link for "Community Support" in the lumina-info utility which will open the webclient in the users browser.
2) Desktop/menu entry for the same action (just need to think of a name/title for it: "Lumina Support"?)

What do you think?

**Comment by rockworldmi** [comment]
Freenode web client is down for me as well. 
- Desktop entry would be nice for new users. "Lumina Support" seems good.
- Also welcome screen can be also useful with few more weblinks to different documentations.

**Comment by beanpole135** [comment]
Done!
The Freenode IRC webclient seems to be back up as well, so I verified the URL beforehand.

https://github.com/pcbsd/lumina/commit/2a903e0abe094e3f5da28bddd325dd67b28446c4
