### ISSUE TITLE
build fails on linux 64 bit

### ISSUE THREAD

**Issue by sixsixfive** [pcbsd/lumina#170]
Something goes wrong here on Linux amd64 Qt 5.5.1

once i add the PREFIX=/usr var everything goes wrong

output of /usr/lib/qt5/bin/qmake PREFIX=/usr -o Makefile lumina.pro

http://pastebin.com/pFqc5X3P

if I dont add a prefix it builds fine.

**Comment by beanpole135** [comment]
Strange - those are all internal Qt declarations which are failing.
Try this qmake command instead: `/usr/lib/qt5/bin/qmake CONFIG+="PREFIX=/usr" lumina.pro`

**Comment by sixsixfive** [comment]
>Try this qmake command instead

that did it, thx ;)
