### ISSUE TITLE
lumina-desktop.org is offline

### ISSUE THREAD

**Issue by boustanihani** [pcbsd/lumina#171]
http://lumina-desktop.org/ **is offline**

**Comment by rbns** [comment]
it seems that one of the nameservers registered for the domain doesn't have the record for lumina-desktop.org. i've mailed the contact for the domain about this.

**Comment by bittin** [comment]
Seems to be back up now :)
and Swedish translation is 99% done updated everything, just 2 strings left

**Comment by boustanihani** [comment]
for me it is still offline, I'm in Germany/Berlin

**Comment by bittin** [comment]
its up from Sweden via Telia as ISP

**Comment by beanpole135** [comment]
Try it again now. We just moved the Lumina website over to a new server hosted by the PC-BSD project (instead of having it run in a small VM), and the DNS registration changes seem to be lagging quite a bit behind in some areas.

**Comment by boustanihani** [comment]
still offline :(

**Comment by rbns** [comment]
it is too still down for me. whois returns NS1.IXSYSTEMS.COM and 
NS2.IXSYSTEMS.COM for lumina-desktop.org.
here's the output of dig at these nameservers registered for the domain:

; <<>> DiG 9.9.8-P2 <<>> @NS1.IXSYSTEMS.COM lumina-desktop.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36271
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;lumina-desktop.org.		IN	A

;; AUTHORITY SECTION:
lumina-desktop.org.	86400	IN	SOA	ns1.ixsystems.com. hostmaster.ixsystems.com. 2015120401 28800 7200 604800 86400

;; Query time: 163 msec
;; SERVER: 64.62.136.40#53(64.62.136.40)
;; WHEN: So Dez 20 19:50:05 CET 2015
;; MSG SIZE  rcvd: 111

; <<>> DiG 9.9.8-P2 <<>> @NS2.IXSYSTEMS.COM lumina-desktop.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35909
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;lumina-desktop.org.		IN	A

;; AUTHORITY SECTION:
lumina-desktop.org.	86400	IN	SOA	ns1.ixsystems.com. hostmaster.ixsystems.com. 2015120401 28800 7200 604800 86400

;; Query time: 177 msec
;; SERVER: 74.7.241.142#53(74.7.241.142)
;; WHEN: So Dez 20 19:50:31 CET 2015
;; MSG SIZE  rcvd: 111

**Comment by beanpole135** [comment]
Yeah, I see this as well.
I have informed the maintainer of the website about this issue, and it will hopefully be back up shortly.

**Comment by bittin** [comment]
Seems to be back up new worked from my grandparents ISP: Tele2 4g in Sweden

**Comment by boustanihani** [comment]
its back :)
