### ISSUE TITLE
[RFE] Switch to CMake

### ISSUE THREAD

**Issue by Conan-Kudo** [pcbsd/lumina#174]
Have you guys considered moving from qmake to CMake for the build system? It would make it much easier to build correctly on various Linux and non-Linux *nix platforms, due to its more advanced detection and configurability, without being the pain that autotools is. 

Importantly, it would allow managing which files get included in the build process depending on which OS and distribution it is being built for, making the process much simpler than it is now (where separate scripts must be run to prepare it for an OS/distribution).

QMake is a pain to deal with as a packager because it tends to be somewhat finicky, and due to the influence of KDE on Qt, Qt has extremely strong support for projects built and developed using the CMake build system. It's also increasingly quite popular, notably being used as the project format for the CLion IDE and is supported by recent versions of Qt Creator directly.

**Comment by beanpole135** [comment]
I have no plans to move to CMake anytime in the near future. 
I think the main source of problems is not cmake vs qmake, but instead the cross-OS build format for Lumina just need to be cleaned up and simplified. The current system was the original qt4 prototype - with new methods getting added in whatever format the contributor was familiar with (shell script, qmake variables, or C++ defines). This has caused the cross-OS build system get quite muddled over time and it is due for a clean up. 
I will start working on cleaning it up this week and see if I can streamline it to a single framework (qmake project file most likely - that is the easiest way to make build-time adjustments later on).

Here is what I am thinking of  off-hand:
1) Setup a much finer-grained list of build-time variables for all the project files. For example, this is all the current variables (PREFIX, LIBPREFIX, INCLUDEPATH, LINUX_DISTRIBUTION, DESTDIR, etc...) as well as any new variables for finer control.
2) Setup OS "macros" for the build system in the overall "lumina.pro", so the entire project can be built with just a single "qmake CONFIG+=OS=<something>". This would allow us to setup better default/known build settings for all the various/known OS's for Lumina (and maybe even make the OS auto-detected unless manually specified). Basically this would just pre-set all the various knobs in (1) as needed for the OS.

Thoughts?

**Comment by Conan-Kudo** [comment]
That does sound better...

There's also the aspect of why it needs to be so complex to support different distributions. Most, if not all Linux distributions use common configurations. The main difference among distributions is that [UsrMerge](http://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/) has not yet been implemented by the Debian family, but these definitions could be passed in at build-time to simplify things, right?

Also, there's the [`/etc/os-release` file](http://www.freedesktop.org/software/systemd/man/os-release.html) that can be used to identify and report branding in a standard way. Even systems that don't use systemd include this file because it's a genuinely useful feature. I'm not sure if this file has made its way into the BSDs, but it is a nicely standardized way to identify an OS.

The current way I'm approaching the Fedora brand switching is to add ifdefs to switch to "CentOS Linux" or "Red Hat Enterprise Linux" depending on whether the `__CENTOS__` or `__RHEL__` definitions are passed at compile time. This is likely to get messy as others add their own brands to it (since it's quite easy to swap out Fedora branding). 

Even if you were to retain the current mechanism for supporting different distributions, there's also the question of whether all the fields are necessary. For example, QtConfig doesn't exist for Qt 5 and the Qt4 version has no effect on Lumina now.

**Comment by beanpole135** [comment]
That UsrMerge format is actually Linux-specific - the BSD's have already had a standardized filesystem layout for quite some time and it is not the same as the UsrMerge format (one good example is that all files under /[bin/sbin/blah] are reserved for the OS only, while all port/package files are placed under /usr/local/[bin/sbin/blah]).

Most of the build options for Lumina were actually added so it could be built on various Linux distributions (since the BSD's are so uniform/standardized) - so if they start standardizing the filesystem layout on Linux systems that would make things *much* easier here.

As for the libLumina class/functions itself - I was planning on removing that QtConfig definition here soon anyway - that was a holdover from the Qt4 days and as you pointed out is no longer valid for Qt5.

**Comment by Conan-Kudo** [comment]
As I said earlier, with the notable exception of the Debian family, UsrMerge is pretty much the common format across all Linux distributions. Fedora, openSUSE, Arch, etc. all follow it. That said, if it's possible to set the App Prefix and the Sys Prefix as a qmake compile time variable, that would make things simpler, too.

**Comment by beanpole135** [comment]
Ok, I have the basic shell of an abstracted-out OS build system setup now - please take a look and let me know what you think.
I am still planning on extending it farther (distinct install dir definitions for bins, libs, include files, config files, etc... - then propagate those into the Lumina library definitions) but this at least is a good start. It already replaces the need for the "make-linux-distro.sh" script - but I want to do some more testing before I remove that script.

https://github.com/pcbsd/lumina/commit/85d9932824853a4567bf37d6ed2f6d2ab2b6ba05
