### ISSUE TITLE
Sound Volume does not stay constant

### ISSUE THREAD

**Issue by texstar** [pcbsd/lumina#180]
After setting the Volume then clicking on Preferences from the menu causes the volume to decrease in value each time Preferences is selected until it stops at 13%.

**Comment by beanpole135** [comment]
I am unable to reproduce this on a FreeBSD system, so could you let me know which OS build setting you are using (running qmake on the source tree will result in a "Build Settings Loaded: <OS Name>" message). 

This almost sounds like your system is returning the wrong system volume when Lumina asks for the current levels (using "amixer" on Linux/Debian, "mixer" on FreeBSD/DragonFly, or "mixerctl" on OpenBSD), or the OS-based audio routine in the library has an error in reading the value for your OS/system.

**Comment by texstar** [comment]
Project MESSAGE: Build OS Info: Linux, x86_64, #1 SMP Sun Jan 31 20:10:02 CST 2016
Project MESSAGE: Build Settings Loaded: Linux -PCLinuxOS

Swapping out the following from LuminaOS-Linux.cpp fixed our mixer volume from decreasing each time the Preferences button was selected. Thank you for the hint to look at the amixer routines.

-  QString info = "amixer -c 0 sset Master,0 " + QString::number(percent) + "%";
+  QString info = "amixer set Master " + QString::number(percent) + "%";

**Comment by beanpole135** [comment]
Thanks for working that out! 
I just commited your change to that command in the LuminaOS-Linux file (master branch only).
