### ISSUE TITLE
Critical bug in libluminautils1 package (Debian)

### ISSUE THREAD

**Issue by Sunderland93** [pcbsd/lumina#184]
Hello. After packaging Lumina 0.8.8, i installed it on Debian 8. But when configure libluminautils1 package, dpkg giving error "trying to overwrite directory '/usr/lib/x86_64-linux-gnu' in package libluminautils1_0.8.8-1.deb with nondirectory. I look into package, and found BINARY file x86_64-linux-gnu 

![1](https://cloud.githubusercontent.com/assets/11344982/13031939/d037189c-d31a-11e5-9908-c7688c0b7874.png)

what is the problem?

**Comment by Sunderland93** [comment]
PR #185 fix this error. This is because the libluminautils1.so.0.0 is copied to a nonexistent directory. Line `install -m755 -d $(CURDIR)/debian/libluminautils1/usr/lib/$(DEB_HOST_MULTIARCH)` in debian/rules file adds it

**Comment by beanpole135** [comment]
Patch merged into "master" branch. Thanks for fixing that!
