### ISSUE TITLE
Window titles in the taskbar are not updated

### ISSUE THREAD

**Issue by larsengels** [pcbsd/lumina#186]
The window titles in the task bar are not updated automatically. I need to mouse-over on a task bar entry so that the new name appears.

The same is true for the workspace changer which is also only updated "manually".

Environment:

    $ pkg info lumina
    lumina-0.8.8,1
    Name           : lumina
    Version        : 0.8.8,1
    Installed on   : Mon Feb 15 17:28:09 2016 CET
    Origin         : x11/lumina
    Architecture   : freebsd:11:x86:64
    Prefix         : /usr/local
    Categories     : x11
    Licenses       : BSD3CLAUSE
    Maintainer     : kmoore@FreeBSD.org
    WWW            : http://lumina-desktop.org
    Comment        : Lumina Desktop Environment
    Options        :
            MULTIMEDIA     : on
            PCBSD          : off
    Shared Libs required:
            libxcb-composite.so.0
            libxcb-damage.so.0
            libQt5X11Extras.so.5
            libQt5Gui.so.5
            libQt5Core.so.5
            libxcb-ewmh.so.2
            libGL.so.1
            libXdamage.so.1
            libxcb-image.so.0
            libQt5Concurrent.so.5
            libQt5Widgets.so.5
            libxcb-util.so.1
            libQt5Network.so.5
            libxcb-icccm.so.4
            libQt5Multimedia.so.5
            libQt5Svg.so.5
            libxcb.so.1
            libQt5MultimediaWidgets.so.5
    Shared Libs provided:
            libLuminaUtils.so.1
    Annotations    :
            repo_type      : binary
            repository     : FreeBSD
    Flat size      : 11.8MiB
    Description    :
    Lumina-DE is a lightweight, BSD licensed desktop environment,
    designed specifically for use on FreeBSD
    
    WWW: http://lumina-desktop.org

**Comment by beanpole135** [comment]
Fixed!
Looks like the Lumina session was simply not getting any property change notifications from the X subsystem for the task manager windows.

https://github.com/pcbsd/lumina/commit/21704e5eb19053087a0b080fcdb7a452cf7526f9
