### ISSUE TITLE
Feature suggestion: quickly jump to files / directories using the keyboard in lumina-fm 

### ISSUE THREAD

**Issue by larsengels** [pcbsd/lumina#189]
It would be very helpful if lumina-fm selected the first hit when a key is pressed.

For example in / pressing "u" selects "usr", "v" selects "var" etc.

**Comment by larsengels** [comment]
Hmm, playing around some more it is already implemented. But it didn't work when I wrote this PR. ;)

**Comment by beanpole135** [comment]
The type-to-find functionality requires that the main tree/list widget have keyboard focus first (restriction caused by the multiple tabs/columns functionality). That is probably why you did not notice it originally.

:-)
