### ISSUE TITLE
OS-detect.pri doesn't honor PREFIX and other parameters

### ISSUE THREAD

**Issue by krytarowski** [pcbsd/lumina#195]
Currently `OS-detect.pri` wrongly overwrites and sets PREFIX (and others) to hard-coded paths. It's not possible to overwrite them.

This section never happens to have defined PREFIX:

```
  #Setup the default values for build settings (if not explicitly set previously)
  !defined(PREFIX){ PREFIX=/usr/local }
  !defined(LIBPREFIX){ LIBPREFIX=$${PREFIX}/lib }
```

Later on we overwrite these values and others with per-OS options.

pkgsrc is a multiplatform framework and this doesn't work. We need to uniformly pass PREFIX LDFLAGS CFLAGS etc.

While there LIBS is broken too. We need to set these options via make call and via LDFLAGS, not via hard-coded values. We set there paths like rpath or custom ones like /usr/X11R7/lib/ provided by pkgsrc.

My qmake call is as follows:

```
pre-build:
        ${RUN} cd ${WRKSRC} && ${QTDIR}/bin/qmake PREFIX=${PREFIX} CONFIG+="configure NO_I18N"
```

Please improve it.

Once done, I will cherry-pick the patch and push Lumina for new pkgsrc. Other than that, it builds on NetBSD.

**Comment by beanpole135** [comment]
I think you just need to move the "PREFIX=${PREFIX}" line (and any other definitions like LDFLAGS/CFLAGS) into the CONFIG+= section. If I recall, that was a change with qmake in Qt5 that caught me on FreeBSD as well.

**Comment by krytarowski** [comment]
It's not sufficient. Please honor provided PREFIX and other parameters in build-machinery.

Thanks!

Here is an example, the default prefix for pkgsrc is `/usr/pkg` in the privileged mode. The scripts resets it to `/usr/local`:

```
$ make stage-install
=> Bootstrap dependency digest>=20010302: found digest-20121220
===> Installing for lumina-0.8.8
=> Generating pre-install file lists
cd libLumina/ && ( test -e Makefile || /usr/pkg/qt5/bin/qmake /tmp/pkgsrc-tmp/wip/lumina/work/lumina-0.8.8-Release/libLumina/libLumina.pro 'CONFIG+=configure NO_I18N PREFIX=/usr/pkg' -o Makefile ) && /usr/bin/make -f Makefile install
libtool --silent --mode=install cp "libLuminaUtils.la" "/tmp/pkgsrc-tmp/wip/lumina/work/.destdir/usr/local/lib"
libtool: install: warning: remember to run `libtool --finish /usr/local/lib'
install -m 644 -p /tmp/pkgsrc-tmp/wip/lumina/work/lumina-0.8.8-Release/libLumina/LuminaXDG.h /tmp/pkgsrc-tmp/wip/lumina/work/.destdir/usr/local/include/
install -m 644 -p /tmp/pkgsrc-tmp/wip/lumina/work/lumina-0.8.8-Release/libLumina/LuminaUtils.h /tmp/pkgsrc-tmp/wip/lumina/work/.destdir/usr/local/include/
install -m 644 -p /tmp/pkgsrc-tmp/wip/lumina/work/lumina-0.8.8-Release/libLumina/LuminaX11.h /tmp/pkgsrc-tmp/wip/lumina/work/.destdir/usr/local/include/
install -m 644 -p /tmp/pkgsrc-tmp/wip/lumina/work/lumina-0.8.8-Release/libLumina/LuminaThemes.h /tmp/pkgsrc-tmp/wip/lumina/work/.destdir/usr/local/include/
install -m 644 -p /tmp/pkgsrc-tmp/wip/lumina/work/lumina-0.8.8-Release/libLumina/LuminaOS.h /tmp/pkgsrc-tmp/wip/lumina/work/.destdir/usr/local/include/
```

**Comment by krytarowski** [comment]
Thanks, but this issue is still valid. It's better but still not right - there are still symbols overridden for platforms, including NetBSD (notably `LIBPREFIX`). pkgsrc runs on all of the platforms available for Lumina and we need to be able to overwrite these values for all of them.

**Comment by krytarowski** [comment]
I bet this block should be removed completely:

```
   # Now go through and setup any known OS build settings
   # which are different from the defaults
   equals(QMAKE_HOST.os, "DragonFly"){
     #Note: DragonFly BSD gets detected as FreeBSD with compiler flags ?
     OS = DragonFly
     LIBS += -L/usr/local/lib -L/usr/lib
     
   }else : freebsd-*{
     OS = FreeBSD
     LIBS += -L/usr/local/lib -L/usr/lib
      #Use the defaults for everything else
     
   }else : openbsd-*{
     OS = OpenBSD
     LIBS += -L/usr/local/lib -L/usr/lib
     #Use the defaults for everything else
     
   }else : netbsd-*{
     OS = NetBSD
     LIBS += -L/usr/local/lib -L/usr/lib
     LIBPREFIX=/usr/local/lib
     #Use the defaults for everything else
     
   }else : linux-*{
     L_SESSDIR=/usr/share/xsessions
     OS=Linux
     LIBS += -L/usr/local/lib -L/usr/lib -L/lib
     
     exists(/bin/lsb_release){
       LINUX_DISTRO = $$system(lsb_release -si)
     } else:exists(/usr/bin/lsb_release){
       LINUX_DISTRO = $$system(lsb_release -si)
     }
   }else{ 
     OS="Unknown"; 
   }
```

If we need it, than just for querying OS.

**Comment by beanpole135** [comment]
krytarowski: Why don't you just modiy the netbsd section of that file as you need, then send in a patch? I can understand why the LIBPREFIX line should probably be removed, but as for your special packaging variables I can't really do any tests/verification of them since I don't have any NetBSD systems.

**Comment by beanpole135** [comment]
Ok, I just pushed up a couple fixes to the project files:
1) I removed that LIBPREFIX definition from the NetBSD section
2) I cleaned up the use of the DESTDIR variable. This variable should be used in situations where the files are getting temporarily installed into an alternate subdir (such as a clean working dir), before getting packaged up. The PREFIX variable should still be used for the final *installed* prefix, since that is required for some internal linking/paths at binary runtime.

Example:
If DESTDIR is set to "/usr/pkg" with PREFIX="/usr/local/", then the Lumina files will get installed (without other OS-specific path modifications) to "/usr/pkg/usr/local/[bin/sbin/etc/lib/share/include]". However, the binaries at runtime will expect themselves to be installed into "/usr/local/[bin/sbin/share/lib/etc/include]" (particularly the share/etc dirs), so some other system (such as a package installer) will need to move the files into the proper places prior to running the binaries.

If you need other special automated-build settings/knobs, you just need to give me a list and I can add more in for you.

Commit:
https://github.com/pcbsd/lumina/commit/bd29fc775f54ce78b0e99c84f6077997c976e565

**Comment by krytarowski** [comment]
Thank you! I will test it and give you feedback.

I wasn't proposing PR since I didn't want to introduce decisions on my own in the build-machinery.

**Comment by rezso** [comment]
In addition, LuminaOS.h is installed with:
_static QString LuminaShare(){ return (L_SHAREDIR+"/Lumina-DE/"); }_, but the L_SHAREDIR is not defined.

**Comment by krytarowski** [comment]
It would be nice to pass all these hard-coded in source-code paths to '/usr/local' and other prefixes via single qmake call. Right now I'm using sed-like utility to replace strings with these paths.

**Comment by beanpole135** [comment]
rezso: 
The L_SHAREDIR variable is defined via the qmake initialization routine (See "OS-detect.pri", lines 90-92). That is how the user/OS paths are passed through into the C++ files for usage.

krytarowski:
The whole point of this new system was to allow any build for a particular operating system (not just automated package builders, but local users as well) to simply run "qmake; make; make install" without any special CLI/build flags. The whole point is that for each OS, Lumina should be getting installed/run from the exact same directories irrespective of whether it was installed directly from the Lumina sources or via some pre-built package. If there *are* differences between your pkg install and a local compilation/install, please let me know so we can add additional hooks/paths for things as needed.

**Comment by rezso** [comment]
@beanpole135 yes, I know, and it works for the compilation. But please take a look into the _installed_ LuminaOS.h file.

**Comment by beanpole135** [comment]
rezso: Ah, I see what you mean. If you then try to compile some *other* application and link in the Lumina library, then that variable will not be defined and will cause the compile to fail. I will move that function source into the .cpp files instead in just a moment, which should ensure that the library/compiled value is always used - even when another app is trying to compile against the Lumina lib.

**Comment by beanpole135** [comment]
Done!

https://github.com/pcbsd/lumina/commit/489c21960fceb325d43e31d289b6518f48f39d26
