### ISSUE TITLE
Weird hardcoded paths

### ISSUE THREAD

**Issue by rezso** [pcbsd/lumina#197]
lumina-desktop/defaults/luminaDesktop.conf:
#session_default_terminal=xterm 
#session_default_filemanager=lumina-fm
but
#session_default_webbrowser=/usr/local/share/applications/firefox.desktop
#session_default_email=/usr/local/share/applications/thunderbird.desktop

lumina-fileinfo/MainUI.ui:
../../../../usr/local/share/icons/gnome/32x32/actions/gnome-run.png
../../../../usr/local/share/icons/gnome/32x32/places/folder.png
../../../../usr/local/share/icons/gnome/32x32/categories/xfce-graphics.png
so the fileinfo main ui depends on gnome icon theme.

**Comment by beanpole135** [comment]
The lumina-desktop/defaults/luminaDesktop.conf lines you pasted are just comments/samples of how to create entries (full paths to *.desktop, binaries, etc...). The "#" at the front of the line indicates that it is a comment (typical shell syntax).

The UI resources are probably some kind of internal leftover from the QtDesigner utility. They are only  treated as suggested paths for an initial icon file, and do not actually depend on the gnome icon theme (those paths are ignored/replaced when the app starts up anyway). However, just for consistency I will go through the ui file and clean that up for you here in a minute.

**Comment by rezso** [comment]
Thank you, it's clear for me now.
But I build a package from the source, and I grepped the /usr/local paths in the source, because the /usr/local paths not allowed in the package.
(See the Fedora's spec file, lines 194-200: https://github.com/pcbsd/lumina/blob/master/lumina-desktop.spec#L194
