### ISSUE TITLE
problems with choosing default file manager

### ISSUE THREAD

**Issue by abelbabel** [pcbsd/lumina#199]
Due to issue #198 I wanted to use caja (mate file manager) instead. Firstly, it was not possible to choose it via lumina's configuration utility for default applications. There is a caja.desktop or caja-browser.desktop file in /usr/local/... , but it does not show up in the list where to choose the applications. Secondly, when I manually edit the directory setting in `~/.lumina/LuminaDE/lumina-open.conf` it works for a while, but gets changed randomly upon reboots or re-logins to something else (not caja-browser anymore).

**Comment by beanpole135** [comment]
Ok, see if this works better for you now.
I just switched Lumina over to using the "inode/directory" mimetype for registering the default file manager application (~/.config/lumina-mimetypes.list - per FreeDesktop specifications).

https://github.com/pcbsd/lumina/commit/cdc5e2e146ac7bbe68731b3090225fc84e3a1b5d
