### ISSUE TITLE
Button issue in lumina-screenshot

### ISSUE THREAD

**Issue by q5sys** [pcbsd/lumina#211]
Within MainUI.ui  there is a 'gap' before the 'Snap' button.
I tried to reorder them to fit the typical workflow within applications.
ie. new always being at the far left of a toolbar, next being open (not applicable in this application), then save functions, then all the edit functions, and quit always being at the far upper right.
Since that is the typical known order of things in virtual every program I tried to mirror that same order in the screenshot utility.

 I tried to re-order lines  157 to 161 from:
```
   <addaction name="actionSave"/>
   <addaction name="actionquicksave"/>
   <addaction name="actionEdit"/>
   <addaction name="actionNew"/>
   <addaction name="actionQuit"/>
```

to 
```

   <addaction name="actionNew"/>
   <addaction name="actionSave"/>
   <addaction name="actionquicksave"/>
   <addaction name="actionEdit"/>
   <addaction name="actionQuit"/>
```

However no matter where I place "actionNew" in the order, there is always a dead gap in front of it.  I've search through the source of everything else and can't seem to find the reason for this gap.  Ideally the gap could be between Edit and Quit... but I cant seem to make that work.  Is there something else causing this gap behavior?

**Comment by beanpole135** [comment]
That is because there is a spacer widget placed in front of the actionNew item within the MainUI.cpp code (lines 17-19). If you are going to re-arrange the toolbar actions you will probably need to move that spacer as well.
