### ISSUE TITLE
Makefile:151: recipe for target 'sub-lumina-fm-make_first' failed

### ISSUE THREAD

**Issue by fr0zi** [pcbsd/lumina#216]
Hello guys,

I'm trying to compile Lumina on Gentoo Linux from git source (I couldn't find ready-to-use ebuild in portage tree).

I cloned git repository, run qmake and invoked make, but I got these errors:

MainUI.cpp: In constructor ‘MainUI::MainUI()’:
MainUI.cpp:117:17: error: no matching function for call to ‘MainUI::~MainUI()’
MainUI::~MainUI(){
                 ^
MainUI.cpp:117:17: note: candidate is:
In file included from MainUI.cpp:7:0:
MainUI.h:68:2: note: virtual MainUI::~MainUI()
  ~MainUI();
  ^
MainUI.h:68:2: note:   candidate expects 1 argument, 0 provided
MainUI.cpp:126:22: error: qualified-id in declaration before ‘(’ token
 void MainUI::OpenDirs(QStringList dirs){
                      ^
MainUI.cpp:924:1: error: expected ‘}’ at end of input
 }
 ^
Makefile:583: recipe for target 'MainUI.o' failed
make[1]: *** [MainUI.o] Error 1
make[1]: Leaving directory '/home/frozen/Devel/lumina/lumina-fm'
Makefile:151: recipe for target 'sub-lumina-fm-make_first' failed
make: *** [sub-lumina-fm-make_first] Error 2

I see on Git that MainUI files in lumina-fm folder were changes recently.
Maybe the issue was made then?

Thanks for help in advance.

**Comment by q5sys** [comment]
Yes, there was an errorr on my part that caused this error.  I've already submitted a pull request to resolve the issue. If your need is urgent, check out the open pull request for how to fix it manually until the pull is merged.

**Comment by fr0zi** [comment]
Thanks for fast reaction :)

Yes, that fixed the issue, however now I have another error:

MainUI.cpp:921:6: error: redefinition of ‘void MainUI::resizeEvent(QResizeEvent*)’
 void MainUI::resizeEvent(QResizeEvent *event){
      ^
In file included from MainUI.cpp:7:0:
MainUI.h:165:7: note: ‘virtual void MainUI::resizeEvent(QResizeEvent*)’ previously defined here
  void resizeEvent(QResizeEvent *event){
       ^
Makefile:583: recipe for target 'MainUI.o' failed
make[1]: *** [MainUI.o] Error 1
make[1]: Leaving directory '/home/frozen/Devel/lumina/lumina-fm'
Makefile:151: recipe for target 'sub-lumina-fm-make_first' failed
make: *** [sub-lumina-fm-make_first] Error 2

But there is no rush - it's not urgent :) I will wait till it's fixed :)

**Comment by q5sys** [comment]
That's the 2nd commit listed in that pull request.  https://github.com/pcbsd/lumina/pull/215/commits/6d0d1bd178f62525177a82de7ba2681b3e32ca5e

There are two resize event functions in the lumina-fm source tree and until I can boot back into PCBSD (in linux currently) I'm not able to check my local sources to see which I had removed.

**Comment by beanpole135** [comment]
The pull request q5sys mentioned has just been merged into the source tree.
