### ISSUE TITLE
Desktop does not resize with VirtualBox window

### ISSUE THREAD

**Issue by outpaddling** [pcbsd/lumina#217]
Running  Lumina (0.8.8_2,1) in a FreeBSD 10.3 VirtualBox guest, the desktop still doesn't resize when the VirtualBox window is resized.

A snapshot of the problem is available here:

[https://forums.freebsd.org/threads/54556/](https://forums.freebsd.org/threads/54556/)

Happy to help test patches or suggestions.

Thanks,

    Jason

P.S.  This desktop is really well designed!  Looking forward to switching over from XFCE (which I've been pretty happy with) once a few more issues are worked out.

**Comment by beanpole135** [comment]
A couple things about VirtualBox:
1) Make sure you are using the virtualbox graphics driver within the guest system. Otherwise VB window resizes will not get propagated into the X environment within the guest.
2) Even with the VB driver used, sometime the changes are still not propagated into the guest system properly (ACPI/other issues on FreeBSD?) - resulting in X not being aware of the changes. You can always run "xrandr -q" within the guest at any time to see what the current resolution is for X.

The Lumina bugs with the panels being misplaced and/or not detecting when the X session was modified have already been fixed. If you rebuild Lumina from the current master sources (0.9.0-devel), then you should not have any problems on that front.

**Comment by outpaddling** [comment]
Thanks for the tips.  I'm certain that the X11 is configured correctly 
as resizing works with other desktops such as XFCE and MATE.  The issues 
are not limited to VBox either, as they occur when resizing on a bare 
metal installation.

I'll look forward to trying out 0.9.0 ASAP.

Regards,

      JB

**Comment by outpaddling** [comment]
I just installed from the latest commit and I'm still seeing the problem.  Note that this is not a VirtualBox guest.  I simply resized the screen on my desktop system.  Going to Preferences/Panels, changing something, and saving restores the desktop to normal (panel at bottom of screen).

My modified port is available here: https://github.com/outpaddling/freebsd-ports-wip

![lumina](https://cloud.githubusercontent.com/assets/11299711/14531752/323d8aca-0224-11e6-9d83-b918fdbff0dd.png)

**Comment by beanpole135** [comment]
How are you changing your screen BTW?
I have been testing this with xrandr quite a bit today (even on multiple monitors, with multiple panels per monitor), and I can't reproduce the problem with the latest 0.9.0-devel.
What version does the "lumina-info" uility say you are running?

**Comment by outpaddling** [comment]
I had been right-clicking on the desktop and choosing Preferences/Display.  I just tried xrandr and got the same results as you can see in the screen shot.

So the question is what are the possible variables between your system and mine that might cause this?

I'm running 10.3-RELEASE amd64, latest packages as of this morning.

Are you using any modified dependencies?

FreeBSD sculpin.acadix  bacon ~ 165: pkg info --dependencies lumina
lumina-7f78a894e72db03740068420edb31b20b4bc159d:
        qt5-x11extras-5.5.1
        qt5-gui-5.5.1
        libXdamage-1.1.4_3
        fluxbox-1.3.7
        qt5-multimedia-5.5.1
        numlockx-1.2
        qt5-buildtools-5.5.1
        xbrightness-0.3
        qt5-svg-5.5.1
        xorg-7.7_2
        qt5-linguist-5.5.1
        xscreensaver-5.34
        qt5-concurrent-5.5.1
        libX11-1.6.3,1
        qt5-network-5.5.1
        fluxbox-tenr-styles-pack-20071215_3
        kde4-icons-oxygen-4.14.3
        qt5-core-5.5.1
        desktop-file-utils-0.22_3
        gstreamer1-plugins-core-1.4.0
        qt5-imageformats-5.5.1_1

My panel is normally at the bottom of the screen, BTW.

![lumina](https://cloud.githubusercontent.com/assets/11299711/14581345/2f06d432-03b0-11e6-9f34-cf7854b17f07.png)

**Comment by beanpole135** [comment]
I see you were using Git version 7f78a894e.... (April 13). There were a few changes to the desktop and lumina-xconfig on April 15th which might have already fixed the problem. Could you rebuild from the latest sources and try it again?

**Comment by outpaddling** [comment]
Still no dice...  :-(

Is there any info I can provide on my systems that might help you track this down?

![lumina](https://cloud.githubusercontent.com/assets/11299711/14643372/c3a543fc-0613-11e6-962a-ed1ba154c45d.png)

**Comment by beanpole135** [comment]
what does "xprop -root" return?

**Comment by outpaddling** [comment]
_SCREENSAVER_STATUS(INTEGER) = 0, 1461082673, 0
_QT_CLIPBOARD_SENTINEL(WINDOW): window id # 0x1400002, 0x0
_QT_SELECTION_SENTINEL(WINDOW): window id # 0x1400002, 0x1400002
WM_HINTS(WM_HINTS):
                bitmap id # to use for icon: 0x140000d
[ snip icon renderings ]
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x1400017
_NET_VIRTUAL_ROOTS(WINDOW): window id # 0x80000f
ESETROOT_PMAP_ID(PIXMAP): pixmap id # 0x1200003
_NET_WORKAREA(CARDINAL) = 0, 0, 1280, 988, 0, 0, 1280, 988
_NET_DESKTOP_GEOMETRY(CARDINAL) = 1280, 1024
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0
_NET_CLIENT_LIST_STACKING(WINDOW): window id # 0x80000f, 0x800011, 0x1400017, 0x1800081
_NET_CLIENT_LIST(WINDOW): window id # 0x80000f, 0x800011, 0x1400017, 0x1800081
_NET_DESKTOP_NAMES(UTF8_STRING) = "one", "two"
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_NUMBER_OF_DESKTOPS(CARDINAL) = 2
_NET_SUPPORTED(ATOM) = _NET_WM_STRUT, _NET_WM_STATE, _NET_WM_NAME, _NET_WM_ICON, _NET_WM_ICON_NAME, _NET_WM_STATE_STICKY, _NET_WM_STATE_SHADED, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_HIDDEN, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_MODAL, _NET_WM_STATE_BELOW, _NET_WM_STATE_ABOVE, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_DESKTOP, _NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_ALLOWED_ACTIONS, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_STICK, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_CLIENT_LIST, _NET_CLIENT_LIST_STACKING, _NET_NUMBER_OF_DESKTOPS, _NET_CURRENT_DESKTOP, _NET_ACTIVE_WINDOW, _NET_CLOSE_WINDOW, _NET_MOVERESIZE_WINDOW, _NET_WORKAREA, _NET_RESTACK_WINDOW, _NET_REQUEST_FRAME_EXTENTS, _NET_WM_MOVERESIZE, _NET_FRAME_EXTENTS, _NET_WM_DESKTOP, _NET_DESKTOP_NAMES, _NET_DESKTOP_VIEWPORT, _NET_DESKTOP_GEOMETRY, _NET_SUPPORTING_WM_CHECK
_NET_SUPPORTING_WM_CHECK(WINDOW): window id # 0x100005c
_BLACKBOX_PID(CARDINAL) = 41716
_XROOTPMAP_ID(PIXMAP): pixmap id # 0x1200003
_XKB_RULES_NAMES(STRING) = "base", "pc105", "us", "", ""
XFree86_has_VT(INTEGER) = 1
XFree86_VT(INTEGER) = 9

**Comment by outpaddling** [comment]
Some good news for you...

On a related note, looks like you fixed an issue with the desktop 
crashing when a monitor is added.  I'm going to run this snapshot on my 
laptop for the rest of the week and test it with our projector, and if 
it proves stable enough, I'll showcase Lumina in the parallel 
programming workshop I'm teaching on Saturday.

     JB

**Comment by beanpole135** [comment]
Ok, I finally tracked down this issue and found out that on some systems (related to the graphics driver?) the Qt desktop monitor does not detect/report changes to the X screen layout/sizes. I added a rule to my root window monitor to listen for the changes on the root window directly, and now the desktop properly detects/adjusts to X session changes within VirtualBox instances just fine.

https://github.com/pcbsd/lumina/commit/1e9b663c06a451b215f6fe47e920ff130f4d963a

**Comment by outpaddling** [comment]
Fabulous...  Working fine on my desktop system and in VirtualBox now.

My modified port is available here: [https://github.com/outpaddling/freebsd-ports-wip](https://github.com/outpaddling/freebsd-ports-wip)

Also submitted a [maintainer update](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=209085) for sysutils/desktop-installer that includes a pretty solid default config for Lumina.
