### ISSUE TITLE
Advice on GTK2 app appearance

### ISSUE THREAD

**Issue by outpaddling** [pcbsd/lumina#220]
How does one control the appearance of GTK2 apps under Lumina?

For KDE there is x11-themes/kde-gtk-config.

On my PC-BSD laptop with Lumina, GTK2 and QT apps look similar.

On a FreeBSD box with Lumina, GTK2 apps look like 1990s Motif apps.  I've been digging around a while and so far have come up empty.

Once I figure this out, I'll incorporate it into sysutils/desktop-installer so everyone can enjoy.

Thanks,

   Jason

**Comment by outpaddling** [comment]
Followup:

After some more digging, I discovered x11-themes/lxappearance.  It provides a rather nice interface for changing the GTK2 theme and it shows up in the Lumina browse applications menu.

Default GTK2 theme still looks retro, but at least it's easy to configure now.

Added this and qtcurve-gtk2 to the dev version of desktop-installer and will submit a maintainer update shortly.

If anyone knows of a better way to integrate GTK configuration into Lumina, or how to set a better default theme, I'd love to hear about it.

**Comment by beanpole135** [comment]
Sorry for getting back to you late, but PC-BSD ships with the QtCurve themes for GTK2 and Qt4 (GTK3 and Qt5 look fine without it, but those versions are also available if you want *total* unification). There are other theme engines available as well, and lxappearance is a good one for a graphical management tool (for GTK themes at least).

**Comment by outpaddling** [comment]
Alright, I added the qtcurve packages, lxappearance, and qt4-qtconfig to desktop-installer 0.5.1.

Also figured out how to install a global gtkrc, so the GTK2 appearance will default to qtcurve instead of "Raleigh".  The default setup produced by desktop-installer is looking pretty good now.  This should make Lumina more accessible and inviting to those who aren't on AMD64 or don't want to run PC-BSD for other reasons.

Pending a little more testing, I'll probably submit a maintainer update in a week or so.  For now, it's available in my WIP collection:

[https://github.com/outpaddling/freebsd-ports-wip](https://github.com/outpaddling/freebsd-ports-wip)

**Comment by beanpole135** [comment]
Thanks!
