### ISSUE TITLE
lumina-textedit syntax hilghlight lost when clicking save icon

### ISSUE THREAD

**Issue by mike-pt** [pcbsd/lumina#221]
First nice to know you're working on lumina-terminal and lumina-textedit apps any DE need a terminal and a texteditor.

I just build from master source and tested textedit and found this minor bug.

**Comment by beanpole135** [comment]
Yeah, I am *almost* ready for it to be used on a regular basis. 
I just fixed the syntax highlighting for you though so that it will automatically change the highlighting rules on save *only* if the filename was changed (such as saving a file to disk for the first time).

**Comment by mike-pt** [comment]
:+1:
