### ISSUE TITLE
No window border after screen resize

### ISSUE THREAD

**Issue by outpaddling** [pcbsd/lumina#222]
Following a screen resize, some applications such as xfce-terminal open without window decorations.

I've seen the same issue after adding a monitor/projector on my laptop.

Logging out and back in resolves the issue.

Running commit 80cdfa8494fcec4fce3b593777788fc1a0fdcaf6.

![noborder](https://cloud.githubusercontent.com/assets/11299711/15098224/01de34f6-14fd-11e6-87a2-9b0fdce33d33.png)

**Comment by beanpole135** [comment]
That almost sounds like Fluxbox crashed and could not be restarted. If this happens again, try running "top" or "ps -auwwx | grep flux" just to verify if that is indeed the problem.

**Comment by outpaddling** [comment]
Fluxbox appears to be running fine.  I was seeing fluxbox core files with previous versions, but not anymore.

The problem occurs very consistently on FreeBSD, but only with certain applications.  So far, I've seen it with xfce-terminal and cool-retro-term.

The screenshot here shows applications that were all started AFTER resizing the screen.  Most of them work fine.

Xfce-terminal always gets located in the upper left of the screen and gets stuck at the top layer above all other windows (nothing can overlay it, so I have to close it to get at another window hidden under it).  The menus respond to clicks, but clicking elsewhere on the window doesn't restore focus.  If I go to another window, I have to click on xfce-terminal in the panel to restore focus.

Cool-retro-term does that same thing, but also malfunctions in other ways regardless of screen resizing.  Right now it's showing up as a pink window with no text.  It was working under Lumina a couple weeks ago.

![noborder2](https://cloud.githubusercontent.com/assets/11299711/15215763/c0d1e78a-1819-11e6-8035-ff607ccb4c10.png)

**Comment by beanpole135** [comment]
Strange...
Run "xprop" and click on the window. I wonder if those utilities are setting some special "bypass WM" flag on the window, or if Fluxbox just does not know what to do with them...

**Comment by outpaddling** [comment]
Same symptoms on PC-BSD, BTW:

![pcbsd](https://cloud.githubusercontent.com/assets/11299711/15218263/bfe006c6-1824-11e6-9051-09d7c4992550.png)

**Comment by beanpole135** [comment]
Ok, I just reproduced this here as well, and I don't see any of the special "bypass WM" X11 flags on the window, and Fluxbox is still running and handling other windows fine, so you might need to ask the Fluxbox devs about this (or the xfce-termina/retro-cool-term devs, but I think it is most likely a Fluxbox issue).

**Comment by outpaddling** [comment]
On 05/12/16 09:55, Ken Moore wrote:
>
> Ok, I just reproduced this here as well, and I don't see any of the 
> special "bypass WM" X11 flags on the window, and Fluxbox is still 
> running and handling other windows fine, so you might need to ask the 
> Fluxbox devs about this (or the xfce-termina/retro-cool-term devs, but 
> I think it is most likely a Fluxbox issue).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/pcbsd/lumina/issues/222#issuecomment-218783059>
>
I was able to reproduce this on a VM running just Fluxbox.  I submitted 
a PR on the Fluxbox site.

Regards,

     JB

-- 
All wars are civil wars, because all men are brothers ... Each one owes
infinitely more to the human race than to the particular country in
which he was born.
                 -- Francois Fenelon

**Comment by mike-pt** [comment]
Just bumped into this... as a workaround for now, I just "pkill" fluxbox and then use fluxbox -rc .lumina/fluxbox-int to have fluxbox start as it would from lumina's start and it brings windows decorations back...

Seems to happen more with terminal emulators btw, as I see this mostly with "Sakura" or "gnome-terminal" (not xterm though)
