### ISSUE TITLE
Linux build issue

### ISSUE THREAD

**Issue by thefenriswolf** [pcbsd/lumina#226]
I've encountered an issue with Lumina-desktop-git in the OpenSuse Build Service, where it doesn't build.
This may be caused by loading a C library while the source file is written in C++ [OBS Build Log](https://build.opensuse.org/package/live_build_log/home:metakcahura/lumina-desktop-git/Arch_Extra/x86_64)

**Comment by beanpole135** [comment]
This appears to be an issue with the OBS build service rather than with Lumina. The log makes it look like Qt-core cannot find the C libraries, which is usually a problem with the build environment/settings.

**Comment by mmetak** [comment]
Hello. I'm the owner of that OBS project page and the issue seems to be related to new gcc 6 on archlinux and not the Open Build Service itself.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129

**Comment by thefenriswolf** [comment]
Oh, I see. Well, I guess I'll just have to wait for the fix.
But thank you for troubleshooting this

**Comment by mmetak** [comment]
@thefenriswolf the fix is to simply put "QMAKE_CFLAGS_ISYSTEM=" to qmake-qt5 and it builds fine.
That's what I did with my updated pkgbuild file in OBS.
