### ISSUE TITLE
Make error during complining 

### ISSUE THREAD

**Issue by Ste74** [pcbsd/lumina#230]
I try to build via Manjaro .. i have error with gcc possible you use an older version than 6.1.1 ?

**Comment by Ste74** [comment]
Well is qmake + gcc issue .. this temporary fix the issue 

qmake QMAKE_CFLAGS_ISYSTEM= PREFIX="/usr" QT5LIBDIR=/usr/lib/qt
make

**Comment by beanpole135** [comment]
This is a known regression in GCC 6.
You now need to pass "QMAKE_CFLAGS_ISYSTEM=<stuff>" to qmake-qt5 before GCC6 will include files from those directories.

Additional Information: https://github.com/pcbsd/lumina/issues/226

**Comment by Ste74** [comment]
Yep .. after my second post i add the flags .. and i have upload a new snapshot for lumina into manjaro :wink: 
Thank you for link to other post i lost it :smile:
