### ISSUE TITLE
Trying to use on OpenBSD 6.0-current

### ISSUE THREAD

**Issue by bceverly** [pcbsd/lumina#231]
Hi,

From the documentation in section 1.1:

Once installed, add start-lumina-desktop as the name of the binary in your .startx, .xinitrc, or similar X startup file

I installed the lumina package on OpenBSD but a:

find / -name 'start-lumina-desktop'

Returns no results.  I looked at the GitHub source repo and don't see a script with that name.  So I dug into the Makefile for the /usr/ports/x11/lumina/lumna package and don't see one being created in there nor do I see it in the PLIST manifest.

Any help would be appreciated in terms of how I actually can run this desktop on OpenBSD.  I love the concept.

Thanks!

**Comment by beanpole135** [comment]
The "start-lumina-desktop" binary is created from the src-qt5/core/lumina-session project within the source tree. It is a new binary (as of 0.9.0), so you might want to ensure that your OpenBSD port has been updated to create/install that binary alongside the main Lumina-DE binary.
