### ISSUE TITLE
LXcbEventFilter.cpp is included in lumina-desktop.pro but it does not exist

### ISSUE THREAD

**Issue by mike-pt** [pcbsd/lumina#32]
Not sure if its missing or if it should be removed from the .pro file!?

**Comment by beanpole135** [comment]
Sorry about that! I have been in the middle of a bunch of XCB flow changes and must have accidentally committed only half of the new event parser. 
Fixed!

https://github.com/pcbsd/lumina/commit/3004b0d22caf1985d5e9b60c7647293f10f5690a
