### ISSUE TITLE
Error while loading shared libraries libLuminaUtils.so.1 cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by crossroads1112** [pcbsd/lumina#36]
Hello,

I am trying to package the Lumina DE for Arch Linux. 

DISCLAIMER: I know that Lumina is targeted at FreeBSD and its derivatives and that Linux is likely not anyone's area of expertise. To make matters worse, I'm pretty new at packaging so I am sorry if this is a dumb question  

Anyway, I followed the instructions and managed to compile and install Lumina without error. However, when I try to run it I get the message in the title of this bug report?

Any ideas?

**Comment by crossroads1112** [comment]
I am an idiot. Of Lumina (being targeted at the FreeBSD and all) would put a bunch of stuff in /usr/local. My bad.

**Comment by beanpole135** [comment]
FYI: Please note the build options listed in the repo information. If you need to change the library directory for some other OS, you just need to make sure to set the "LIBPREFIX" variable when you run qmake.
