### ISSUE TITLE
Change where the makefile looks for lrelease?

### ISSUE THREAD

**Issue by crossroads1112** [pcbsd/lumina#37]
As the title states, is there a way to change where the makefiles look for lrelease without just using sed over all of them? I want it to look for it in PREFIX/bin/lrelease but it is looking for it in LIBPREFIX/qt5/bin/lrelease

EDIT: It looks like it is not in the makefiles but rather in the lumina-\*/lumina-\*.pro files.

**Comment by beanpole135** [comment]
The PREFIX, LIBPREFIX, and QT5LIBDIR variables can all be set/customized through qmake when creating the Makefiles from the *.pro files.
You just need to run something like this when running qmake (for example, used all different locations):
qmake PREFIX=/usr LIBPREFIX=/usr/lib32 QT5LIBDIR=/usr/local/lib/qt5 *.pro
