### ISSUE TITLE
Bug: Window titlebars hidden behind panel on second screen

### ISSUE THREAD

**Issue by bitnapper** [pcbsd/lumina#46]
I use lumina on FreeBSD 10.1 with a dualscreen setup. Problem is, that the titlebars of my windows on the second screen are hidden behind the top panel which prevents me completely from moving windows.

**Comment by beanpole135** [comment]
Which version of Lumina are you using (pkg info | grep lumina)?
There was a fix put in place in version 0.8.1 that moves any windows which are created underneath the panel out into the visible areas of the screen, and version 0.8.2 (source build - still in development) has even more improvements with screen reservations.

**Comment by bitnapper** [comment]
lumina-0.8.1.1421890927,1

**Comment by beanpole135** [comment]
Is this still an issue with Lumina 0.8.[4/5] and Fluxbox 1.3.7? I know that a lot of work went into the Fluxbox window detection/movement routines for 1.3.7, and I can't seem to reproduce this issue on my systems.

**Comment by beanpole135** [comment]
Version 0.8.5-release has a large update to the initial window-geometry adjustment routines which should fix this issue.
