### ISSUE TITLE
Moving and removing panels require a logout

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#51]
I have discvered 2 issues with panels (Openbsd-current, lumina-master both of 13/02/2018)

1)
I add a 2nd panel and add 1 plugin on it (whatever the one you select).
I click to have both top-bottom and click "save changes". 
Problem comes when I come back on the geometry of the panels and ask to have righ-left . Then the top bar remains :(. 
If I change, once again the deometry to top-bottom, the left one remains. 
I must logout and login to have the desired panels. 

2) 
I remove the 2nd panel ad save the changes. 
Here too, I must logout - login to see the corret result. 

Maybe both are related. 

regards

**Comment by beanpole135** [comment]
Sounds like the auto-detection of panel setting changes is not working consistently for some reason (for the second panel in particular). I will take a look at that here soon.

**Comment by beanpole135** [comment]
I just found/fixed this a moment ago. Check it out and see if it works better for you now....

**Comment by william-os4y** [comment]
works great. Thanks
