### ISSUE TITLE
lumina-fm takes 32 seconds to open a folder of 420 jpegs

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#54]
Not sure this is a bug of lumina-fm, because it could be linked to openbsd itself. 
Unfortunately, I'm not able to boot a freebsd installation (10.1) to see it can be reproduced it on freebsd. 
(view detailed list). 
Sounds that he calculates all thumbnails before displaying the files. 

On xfce (with default fm), I've not the same issue. 
I've the impression, that the filemanager displays the file's names first, then calculate the thumbnails (at least for the files displayed on the screen). 

regards

**Comment by beanpole135** [comment]
No, this is a problem with the QFileSystemModel implementation within lumina-fm for which I have been trying to find a work-around (OS-independent). I think eventually I am going to have to write my own filesystem model class to fix this issue (and a couple others involving open file descriptors on removable-media directories), but for the meantime I might add a "display thumbnails" view option so that it can be disabled as necessary to speed things up.

**Comment by beanpole135** [comment]
OK, I just added an option to disable the loading of thumbnails[1]. Note that this does *not* remove the thumbnails that have already been loaded/used, it just prevents loading any more of them (so disable the thumbnails *before* opening that massive directory).

**Comment by william-os4y** [comment]
It works. But we should know in advance that we are entering a folder with lot of pictures.   Thanks. 

Maybe to go around the difficulties,  could we not trigger the thumbnail creation of a specific file when user's mouse goes over a file ?
You could maybe also use this information to trigger thumbnails of the x files around the one detected by the mouseover.

**Comment by beanpole135** [comment]
The "ultimate" solution would be to not load thumbnails when opening a directory, and then load thumbnails afterwards in the background on demand (auto-load thumbnails for all items visible in the frame). 
The problem I am running into is with the QFileSystemModel which lumina-fm uses - there is no way to prompt it to reload information for particular items, and it does not provide access to the item data so I can modify the icon information directly. Now that I have a subclassed version of the QFileSystemModel (for drag and drop support) I might be able to access some more of the internals of the data storage model, but it might take a little bit until I get that working. The current toggle is just to ensure that there was at least a temporary fix in place until I can get the final solution working properly.

**Comment by william-os4y** [comment]
I've pushed a small change that could help users with directories having lot of files. 

The following change display the number of items displayed by lumina-fm's tab in front of the user. 

diff is here: https://github.com/william-os4y/lumina/commit/a5d95ee21de03ee0531847aafe3ab7e37bd517ab

If you think this could be usefull, I can build a pull request. 

I'm hesitating because such feature must be, maybe, included in a more generic feature like the "righ click-> properties" we can find in some filemanagers.

**Comment by william-os4y** [comment]
I've chenged it a little bit :-). 

https://github.com/william-os4y/lumina/commits/fmNumbers

Now it displays the number of items and the size of the displayed files. This is a feature I often use with thumar.

**Comment by beanpole135** [comment]
I think your directory contents info could be combined with the directory capacity routine you mentioned working on in your other issue[1]. Seeing a statistic like that is usually a good addition to the display, as long as it does not slow down the program considerably (so it is better to run it in the background thread).

[1] https://github.com/pcbsd/lumina/issues/73

**Comment by william-os4y** [comment]
Initialy I did it (but not committed). But the big fonts of label_dir_stats, ... is a bit shoking. 
To my eyes, label_dir_stats is great to send "important info" to the user. They are remaing visible. 
In the statusbar, they are indeed replaced by other messages (when going over a button, ...). For me it's fine because those info: # of items, size, capacity are just for info. 
What could be interesting is to move to the label_dir_stats capacity issues (>90% f.e.). 
This is just my 2cents, let me know what you prefer.

**Comment by beanpole135** [comment]
Hum.. that sounds good to me. We can always add new labels to the UI as necessary, so if you want to split the capacity notifications from the directory stats so that we can give different priority to each of them that is completely reasonable.

**Comment by beanpole135** [comment]
Ok, this appears to finally be fixed with the new overhaul of the file manager to *not* use the Qt model/view framework. On my system (with an SSD) I now have a directory of 600+ icon files loading in ~0.5 seconds. On my low-powered laptop (spinning disk HD), that same icon directory loads in ~2 seconds.
The new file manager is currently in the source tree and will be included in 0.8.7-Release.
