### ISSUE TITLE
How to refresh Desktop icons

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#61]
I'm changing the "Icon" parameters of desktop file located in ~/Desktop. 
How can I refresh the desktop ?
The only workaround I've found is to logout and login.

**Comment by beanpole135** [comment]
Hum... I think the desktop view plugin only re-loads the directory if the directory contents are modified - so it won't pick up on changes to individual files. Try creating/deleting a file in your ~/Desktop directory and see if that causes it to refresh.

**Comment by william-os4y** [comment]
indeed. 
I have to move the file out and in of the folder to refresh the icon.
