### ISSUE TITLE
requested feature: would be interesting to display the file/directory name in the bottom of the lumina-fm screen

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#63]
when we select "icon view" in lumina-fm, most of the time the filename (or directory name) is too long. 
So we see the begining of the name. 
Would be nice to display the fullname in the tooltips area when the user goes over (or click 1x) the file

**Comment by beanpole135** [comment]
This is no longer an issue with the new file-manager overhaul for 0.8.7
