### ISSUE TITLE
thumbnail support for .CR2 (RAW Images)

### ISSUE THREAD

**Issue by mike-pt** [pcbsd/lumina#64]
Is this possible as of now with some config change? Or is it something that needs some code changes? If so it would be a nice feature to have.

Not a priority though and I'm guessing it will be pretty slow to load them, but it still better then having to open one by one to just check If I got the right ones :)

**Comment by beanpole135** [comment]
Hum... right now lumina-fm supports all the image/multimedia file formats that Qt supports - so if you find/install the right library for RAW images that Qt can use, then it should just start working the next time you start the file manager.

It almost looks like there is support for additional formats through the Qt "Image Formats" extension[1] - so you might want to poke around there and see if you can add that support on your system.

[1] http://doc.qt.io/qt-5/qtimageformats-index.html

**Comment by mike-pt** [comment]
"qt5-imageformats-5.3.2" is already installed... and looking at the link RAW/CR2 doens't seam to be there...

I do know other file managers make use of libraw.. so I guess I can only hope for a qt 'plugin'/'entention' that makes use of libraw?

In any case... not a lumina issue.

thanks for clarifying

**Comment by mike-pt** [comment]
For reference:
luminance uses libraw (https://www.freshports.org/graphics/luminance-qt5/)
I also found (https://github.com/mardy/qtraw) which also makes use of libraw, failing to compile on freebsd though.
