### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#66]
On Openbsd-current I have the following compilation issue:

/usr/local/lib/libLuminaUtils.so.1.0: undefined reference to `xcb_image_get'
/usr/local/lib/libLuminaUtils.so.1.0: undefined reference to `xcb_image_destroy'

But I find the mehod in /usr/X11R6/include/xcb/xcb_image.h

Sounds this is my fault ... and linked to the libLumina which must be compiled and install first.

**Comment by beanpole135** [comment]
Yes, there was a new library linked into the libLumina.pro file - so you just needed to re-run qmake on the project file to update the Makefile first. The new library is just another one of the small XCB libraries in the standard bundle - so nothing serious should be needed to make sure that library is installed (just install the XCB library bundle - just like before).
