### ISSUE TITLE
lumina-fm not coherent behaviour for the "delete selection"

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#68]
If I select several files and right-click, I can get the checksum of all of them. 
But
If I select several files, the "delete selection" we have on the same menu just delete 1 file. 
(to delete the real selection we must click onthe red cross present on the left of the window OR click on delete on the keyboard). 

Same menu, but different behaviour. 
This could generate some difficulties for some users. 

I must add that the "copy" and "cut" present on the same menu are also taking the whole selection into account.

**Comment by beanpole135** [comment]
Good catch!
Looks like that routine was not converted to multi-selection behavior like most of the others were. Fixed!
