### ISSUE TITLE
Ion size in lumina-fm "home" dir is larger than expected and covers the file/dir names

### ISSUE THREAD

**Issue by mike-pt** [pcbsd/lumina#72]
This is a rather stange issue, but when I open lumina-fm which by default opens in the home dir the size of the icons is very large and I see this in the console:

libpng warning: gAMA: gamma value out of range
QPixmap::scaleHeight: Pixmap is a null pixmap

This only happen with the home dir even if I do "lumina-fm /home/user", any other dir either by browsing or "lumina-fm $dir" show the icons size just fine....

the icon size for the desktop view plugin was also off scale but the decrease size option fixed that.

**Comment by beanpole135** [comment]
I think I just found/fixed this issue[1]. It looks like Qt was resizing the grid/item sizes to a smaller size *only if* one of the icons could not be scaled up to the requested size. 

[1] https://github.com/pcbsd/lumina/commit/18ca7323aa2b3029820cd901feb2854f54899b2f

**Comment by mike-pt** [comment]
Sorry to bring this up, but the issue in this specific report is about lumina-fm too (or mainly) not only desktop-icons (which is indeed fixed) but lumina-fm "Insight" still shows large icons on my homedir and my homedir only, so there must be something about this dir it doesn't like... maybe some hidden "." dir that is messing up things or such...

Opening from shell I only see this:
 "*.rvx", "*.vob", "*.wmv", "*.f4v", "[0-9][0-9][0-9].vdr", "*.mpeg", "*.clpi")
 - done with audio/multimedia checks
 - start searching for base snapshot directory
 - done with base snapshot directory
[miguelc@r2d2:~ ]% lumina-fm
Loading Locale: "lumina-fm" "en_US" "UTF-8"
Loaded QApplication
Change to Tab: 0 "miguelc"
libpng warning: gAMA: gamma value out of range
Starting Dir Checks: "/usr/home/miguelc"
Supported Image Formats: ("*.arw", "*.bmp", "*.cr2", "*.crw", "*.cur", "*.dds", "*.dng", "*.gif", "*.icns", "*.ico", "*.jp2", "*.jpeg", "*.jpg", "*.mng", "*.nef", "*.pbm", "*.pgm", "*.png", "*.ppm", "*.raf", "*.svg", "*.svgz", "*.tga", "*.tif", "*.tiff", "*.wbmp", "*.webp", "*.xbm", "*.xpm")
Supported Multimedia Formats: ("*.ac3", "*.ra", "*.mid", "*.aifc", "*.aiffc", "*.aiff", "*.flac", "*.mka", "*.oga", "*.ogg", "*.wvc", "*.rax", "*.wvp", "*.wvx", "*.m15", "*.mo3", "*.wv", "*.mp+", "*.mp2", "*.mp3", "*.minipsf", "*.xm", "*.xi", "*.mod", "*.aif", "*.mpc", "*.mpp", "*.m3u8", "*.m3u", "*.m4a", "*.m4b", "*.pla", "*.pls", "*.amr", "*.midi", "*.amz", "*.mtm", "*.sid", "*.wav", "*.wax", "*.ape", "*.au", "*.psf", "*.asx", "*.snd", "*.kar", "*.spx", "*.669", "*.awb", "*.ult", "*.s3m", "*.axa", "*.vlc", "*.uni", "*.it", "*.dtshd", "*.psid", "*.stm", "*.dts", "*.wma", "*.voc", "*.psflib", "*.wmx", "*.f4a", "*.f4b", "*.tta", "*.xmf", "*.med", "*.mpga", "*.gsm", "*.aac", "*.webm", "*.rv", "*.qt", "*.3g2", "*.fxm", "*.ts", "*.3ga", "*.3gp2", "*.ogm", "*.mpls", "*.mkv", "*.3gp", "*.ogv", "*.bdm", "*.3gpp", "*.moov", "*.bdmv", "*.divx", "*.mng", "*.mp4", "*.m2ts", "*.m1u", "*.mov", "*.mpe", "*.mpg", "*.mpl", "*.m2t", "*.3gpp2", "*.m4u", "*.m4v", "*.anim[1-9j]", "*.mts", "*.nsv", "*.qtvr", "*.mxu", "*.asf", "*.dv", "*.cpi", "*.viv", "*.avf", "*.flv", "*.flc", "*.avi", "*.fli", "*.axv", "*.vivo", "*.movie", "*.rvx", "*.vob", "*.wmv", "*.f4v", "[0-9][0-9][0-9].vdr", "*.mpeg", "*.clpi")
 - done with audio/multimedia checks
 - start searching for base snapshot directory
 - done with base snapshot directory
 - start fetching snapshots
 - done fetching snapshots
Found snapshots

So apparently no errors, but surely there's some better way to debug this.

**Comment by beanpole135** [comment]
Thanks for letting me know this popped up in lumina-fm too!
I will get that fix for the desktop icons applied to the file manager as well here in a few minutes.... :-)

**Comment by beanpole135** [comment]
Ok - I applied that fix to the file manager as well now - please re-test it and make sure there is nothing else that needs adjusting too.

https://github.com/pcbsd/lumina/commit/bb8538c321dc9eb4257874ec96a1be7c50c28b33

**Comment by mike-pt** [comment]
Fixed, thanks!
