### ISSUE TITLE
What's the goal of emit in CurrentDirectoryLoaded ?

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#76]
void MainUI::currentDirectoryLoaded(){
  //The directory was just loaded: refresh the action buttons as neccesary
  ui->tool_goToPlayer->setVisible(false);
  ui->tool_goToRestore->setVisible(false);
  ui->tool_goToImages->setVisible(false);
  //emit DirChanged(getCurrentDir());
  ItemSelectionChanged();
}

I see that the slot are triggered always 2 times. 
I don't understand the goal to resend and emit in CurrentDirectoryLoaded. 

I've commented it and the application sounds to work correclty.

**Comment by beanpole135** [comment]
That signal emission starts the background worker procedure for checking/enabling any dir-specific things. I needed to have it there to catch the case where the dir is manually refreshed by the user and the model does not emit the "directoryLoaded()" signal (which starts the refresh routine later on). I just put a quick check in to only run that emit when it is the same dir being loaded - this seems to stop all the double-taps on the background process without breaking functionality. If you just comment this first emission out, then the shortcut buttons and such will always be disabled/hidden when you change some setting or view option until you change directories again.

https://github.com/pcbsd/lumina/commit/f8ae4fcc57e5c4020646a0237c0279b2bd0e1780
