### ISSUE TITLE
I want a nice desktop

### ISSUE THREAD

**Issue by NateLing** [pcbsd/lumina#84]
I dont like the Gnome3 and KDE.I really fell gnome2 is a beautifull desktop.
Now,the web site can design very cool.but why the desktop cant.
Lumina Desktop is very young,i wish it become cool and easy!

**Comment by beanpole135** [comment]
This is not a very specific feature request/bug report, so I am closing it. Please be more specific in the future about what you want/need changed.

If you want to get involved in writing additional themes for the Lumina desktop, you can do so through the Lumina configuration utility (lumina-config -> Appearance -> Themes), then send in your customized theme/color files (~/.lumina/themes/* or ~/.lumina/colors/*) for inclusion with the default files shipped with the desktop.
