### ISSUE TITLE
No preview in window theme

### ISSUE THREAD

**Issue by william-os4y** [pcbsd/lumina#94]
On my OpenBsd system I don't have "window theme Preview". 
System says: No preview Available". 

Does this is linked to the setup on OpenBSD (missing files, ...) ?
Does this is linked to a lumina prameter I should adapt ?

**Comment by beanpole135** [comment]
It is just looking for and displaying the "preview.jpg" file contained within the Fluxbox theme directory  for the selected theme.

On FreeBSD, these previews are found in (almost all) of the Fluxbox theme collections, alongside the theme.cfg file (/usr/local/share/fluxbox/styles/<theme name>/preview.jpg). You might want to check and see if those files are stripped out of the OpenBSD package for some reason. If they *are* there, but with a different name/location, let me know and I can adjust the routine to account for it.

**Comment by william-os4y** [comment]
OK. I see it now :-). 

here the package content: 
http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/x11/fluxbox/pkg/PLIST?rev=1.19&content-type=text/x-cvsweb-markup

Indeed, there is no preview.jpg. 

But where are they ?
in the last tar file I don't see them: http://www.fluxbox.org/download/

In the cvs, I don't see them:
http://fluxbox.cvs.sourceforge.net/viewvc/fluxbox/fluxbox/data/styles/

So, they are generated by a tool ?

**Comment by william-os4y** [comment]
I think we can close the issue. 

By installing the following tar file I was able to have previews. 
http://tenr.de/styles/archives/tenr.de-styles-pkg.tar.bz2

Maybe should it be documented somewhere because not all distro/system will provide it defacto. 

thanks

**Comment by beanpole135** [comment]
That would explain it.
The "Tenr styles pack" for Fluxbox has been included/installed with the Lumina port on FreeBSD since day 1, so I simply forgot about it... :-)
